alan_ask_types = {
	"money": [
		"finance_money",
		"finance_info",
		"scam_lottery",
		"scam_gift"
	],
	"information": [
		"personal",
		"business",
		"privileged_information",
		"credentials"
	],
	"performance": [
		"PERFORM"
	]
}

sashank_categories_sensitive = {
   "finance_money":[
      "money",
      "cash",
      "check",
      "bit coin",
      "bitcoin",
      "cheque",
      "euro",
      "euros",
      "dollar",
      "dollars",
      "rupee",
      "rupees",
      "riyal",
      "riyals",
      "$",
      "£",
      "€",
      "₹"
   ],
   "finance_info":[
      "bank",
      "account",
      "transaction",
      "payment",
      "credit card",
      "insurance",
      "transaction",
      "tax",
      "claims",
      "irs",
      "fund",
      "account number",
      "account no",
      "direct deposit",
      "deposit",
      "beneficiary"
   ],
   "personal":[
      "email",
      "e-mail",
      "phone",
      "office address",
      "phone number",
      "contact info",
      "contact information",
      "cv",
      "personal",
      "photo",
      "mobile number",
      "mobile no",
      "phone no",
      "mobile num",
      "phone num",
      "social network",
      "twitter",
      "facebook",
      "social media"
   ],
   "personal_sensitive":[
      "ssn",
      "social security",
      "birthday",
      "citizenship",
      "originally from",
      "home address",
      "signature",
      "date of birth",
      "birth date",
      "day of birth"
   ],
   "business":[
      "proposal",
      "proposition",
      "offer",
      "investment",
      "collaboration",
      "partnership",
      "collusion",
      "business"
   ],
   "credentials":[
      "credentials",
      "password",
      "account",
      "slack id",
      "email id",
      "id",
      "user id",
      "login",
      "slack"
   ],
   "privileged_information":[
      "report",
      "document",
      "attachment",
      "files",
      "intellectual property",
      "brochure",
      "code",
      "form",
      "file",
      "software",
      "project",
      "dropbox",
      "github",
      "google drive",
      "gdrive",
      "excel",
      "word document",
      "word",
      "word doc",
      "doc",
      "slides",
      "presentation",
      "contract",
      "wiki",
      "gitlab",
      "ased",
      "testbed",
      "eval",
      "irb"
   ],
   "ideology":[
      "human rights",
      "jesus",
      "campaign",
      "health",
      "refugee",
      "humanitarian",
      "climate change",
      "cancer",
      "environment",
      "climate",
      "global warming",
      "autism",
      "activist",
      "charity",
      "donation",
      "flyer",
      "event",
      "celebration",
      "awareness",
      "migrant",
      "pet",
      "dog",
      "cat",
      "animal",
      "event",
      "donate",
      "election",
      "disaster",
      "relief"
   ],
   "scam_lottery":[
      "lottery",
      "lucky draw",
      "winner",
      "prize",
      "award"
   ],
   "scam_gift":[
      "gift",
      "present",
      "gift card",
      "gifts card",
      "shop",
      "store"
   ],
   "scam_job":[
      "job",
      "hiring",
      "work experience",
      "interview",
      "candidate",
      "indeed",
      "glassdoor",
      "linkedin",
      "LinkedIn",
      "hackerrank",
      "leetcode",
      "triplebyte",
      "recruiter"
   ],
   "phishing":[
      "link",
      "click here",
      "download",
      "join us",
      "upload here",
      "apply",
      "apply here",
      "surveymonkey",
      "survey monkey",
      "survey gizmo",
      "surveygizmo",
      "doodle",
      "surveyshare",
      "survey",
      "eventbrite",
      "event brite"
   ],
   "work_life":[
      "leave",
      "vacation",
      "sabbatical",
      "training",
      "training notice",
      "notice period",
      "resignation",
      "quit",
      "work from home",
      "family leave",
      "temporary work",
      "temporary work assignment",
      "sick leave"
   ]
}

# These types are not being used currently for sashanks types.
sashanks_ask_types = {
  "finance_money": [
    "11.1 Send Verbs",
    "13.1.a.i Give - No Exchange - Sort of Atelic",
    "13.1.a.ii Give - No Exchange",
    "13.2 Contribute Verbs",
    "13.3 Verbs of Future Having",
    "13.4.1.a Verbs of Fulfilling - Possessional / -to",
    "13.4.1.b Verbs of Fulfilling - Change of State / -with",
    "13.5.1.b.ii Get - Exchange",
    "13.5.2.a Obtain - No Exchange (CAUSE)",
    "13.5.2.b Obtain - No Exchange (LET w/ benefactive)",
	"32.1 Want Verbs"
  ],
  "finance_info": [
    "11.1 Send Verbs",
    "13.3 Verbs of Future Having",
    "13.4.1.a Verbs of Fulfilling - Possessional / -to",
    "13.4.1.b Verbs of Fulfilling - Change of State / -with",
    "13.5.1.b.ii Get - Exchange",
    "13.5.2.b Obtain - No Exchange (LET w/ benefactive)",
    "37.2.a Tell Verbs",
    "37.2.b Tell Verbs / -of/about",
    "37.2.d Tell Verbs / -that/to",
	"32.1 Want Verbs"
  ],
  "personal": [
    "11.1 Send Verbs",
    "13.3 Verbs of Future Having",
    "13.4.1.a Verbs of Fulfilling - Possessional / -to",
    "13.4.1.b Verbs of Fulfilling - Change of State / -with",
    "13.5.2.b Obtain - No Exchange (LET w/ benefactive)",
    "37.2.a Tell Verbs",
    "37.2.b Tell Verbs / -of/about",
    "37.2.d Tell Verbs / -that/to",
	"32.1 Want Verbs"
  ],
  "business": [
    "13.3 Verbs of Future Having"
  ],
  "credentials": [
    "11.1 Send Verbs",
    "13.1.a.ii Give - No Exchange",
    "13.3 Verbs of Future Having",
    "13.4.1.a Verbs of Fulfilling - Possessional / -to",
    "13.4.1.b Verbs of Fulfilling - Change of State / -with",
    "13.5.2.b Obtain - No Exchange (LET w/ benefactive)",
    "37.2.a Tell Verbs",
    "37.2.b Tell Verbs / -of/about",
    "37.2.d Tell Verbs / -that/to",
	"32.1 Want Verbs"
  ],
  "privileged_information": [
    "11.1 Send Verbs",
    "13.1.a.ii Give - No Exchange",
    "13.3 Verbs of Future Having",
    "13.4.1.a Verbs of Fulfilling - Possessional / -to",
    "13.4.1.b Verbs of Fulfilling - Change of State / -with",
    "13.5.2.b Obtain - No Exchange (LET w/ benefactive)",
    "37.2.a Tell Verbs",
    "37.2.b Tell Verbs / -of/about",
    "37.2.d Tell Verbs / -that/to",
	"32.1 Want Verbs"
  ],
  "ideology": [],
  "scam_lottery": [
    "13.5.2.c Obtain - No Exchange (LET w/out benefactive)"
  ],
  "scam_gift": [
    "13.5.2.c Obtain - No Exchange (LET w/out benefactive)"
  ],
  "scam_job": []
}

tomeks_ask_types = {
  "LOSE": [ #verbs may need to be used differently in their passive (subject) vs active form (DO) for this class but not focused on that for now
    "10.5 Verbs of Possessional Deprivation : Steal Verbs",
    "10.6.a Verbs of Possessional Deprivation : Cheat Verbs / -of",
    "10.6.c Verbs of Possessional Deprivation : Cheat Verbs / -out of",
    "17.1 Throw Verbs",
    "17.2.i Pelt Verbs",
    "17.2.ii Pelt Verbs -- stone",
    "18.1.a Hit Verbs - Change of State / -with",
    "18.1.b Hit Verbs - Change of State",
    "18.1.c Hit Verbs  - Locational / -at/with",
    "18.1.d Hit Verbs  - Locational / against",
    "18.1.e Hit Verbs  - Change of State / together",
    "18.2.a Swat Verbs",
    "18.2.b Swat Verbs  - Locational",
    "18.3 Spank Verbs",
    "18.4.a Nonagentive Verbs of Impact by Contact - Locational",
    "18.4.b Nonagentive Verbs of Impact by Contact - Change of State",
    "19.a.i Poke Verbs",
    "19.a.ii Poke Verbs - Change of State",
    "19.b Poke Verbs - Locational / -through",
    "19.c.i Poke Verbs / -with",
    "19.c.ii Poke Verbs - Change of State / -with",
    "19.d Poke Verbs - Locational / -with",
    "29.5.a Conjecture Verbs / -to be"
    #adding these to Steal verbs class for now: "29.5.b Conjecture Verbs / -that", #only some of these verbs ([doubt, suspect, forebode]) but not all!
  ],
  "GAIN": [
    "13.5.1.a Get - No Exchange",
    "13.5.1.b.ii Get - Exchange",
    "13.5.2.a Obtain - No Exchange (CAUSE)",
    "13.5.2.b Obtain - No Exchange (LET w/ benefactive)",
    "13.5.2.c Obtain - No Exchange (LET w/out benefactive)"
    #"32.1 Want Verbs"
  ],
  "GIVE": [
    "11.1 Send Verbs",
    "13.1.a.i Give - No Exchange - Sort of Atelic",
    "13.1.a.ii Give - No Exchange",
    "13.2 Contribute Verbs",
    "13.3 Verbs of Future Having",
    "13.4.1.a Verbs of Fulfilling - Possessional / -to",
    "13.4.1.b Verbs of Fulfilling - Change of State / -with",
    "32.1 Want Verbs"
  ],
  "APPLY": [],
  "PERFORM": [
    "9.1 Put Verbs",
    "10.1 Remove Verbs",
    "10.2.b Banish Verbs / -to",
    "10.5 Verbs of Possessional Deprivation : Steal Verbs",
    "10.6.a Verbs of Possessional Deprivation : Cheat Verbs / -of",
    "10.6.c Verbs of Possessional Deprivation : Cheat Verbs / -out of",
    "11.3 Bring and Take Verbs",
    "13.5.2.d Obtain - Exchange",
		"30.2.a.i Sight Verbs / Bare NP",
    "37.1.e Verbs of Transfer of a Message / -that/to",
    "37.2.a Tell Verbs",
    "37.2.b Tell Verbs / -of/about",
    "37.2.d Tell Verbs / -that/to",
    "37.4.a Verbs of Instrument of Communication",
    "42.1.a Murder Verbs - Kill",
    "42.1.b Murder Verbs - Kill / -with",
    "42.1.c Murder Verbs - General",
    "44.a Destroy Verbs / -with",
    "44.b Destroy Verbs / Instrument Subject",
    "54.4 Price Verbs"
  ],
  "OTHER": []
}
