lose_verbs = [
    "abandon",
    "abash",
    "abhor",
    "absolve",
    "abuse",
    "ache",
    "acquit",
    "afflict",
    "affront",
    "aggravate",
    "agitate",
    "agonize",
    "alarm",
    "alienate",
    "anger",
    "anguish",
    "annihilate",
    "annoy",
    "antagonize",
    "appal",
    "assassinate",
    "assuage",
    "backbite",
    "baffle",
    "balk",
    "bang",
    "bash",
    "bat",
    "batter",
    "beat",
    "beguile",
    "belt",
    "bereave",
    "beware",
    "bewilder",
    "bewitch",
    "bilk",
    "birch",
    "bite",
    "bleed",
    "blitz",
    "bludgeon",
    "boast",
    "boggle",
    "bombard",
    "bonk",
    "bore",
    "boss",
    "bother",
    "brag",
    "brain",
    "brush",
    "buffet",
    "bug",
    "bully",
    "bump",
    "bunt",
    "burgle",
    "butcher",
    "butt",
    "calumniate",
    "cane",
    "care",
    "case",
    "castigate",
    "catapult",
    "censure",
    "chasten",
    "chastise",
    "cheat",
    "chide",
    "chuck",
    "claw",
    "cleanse",
    "clobber",
    "club",
    "complain",
    "con",
    "condemn",
    "confound",
    "confuse",
    "conk",
    "cosh",
    "crab",
    "crash",
    "cripple",
    "criticize",
    "crucify",
    "crush",
    "cry",
    "cudgel",
    "cuff",
    "cull",
    "cure",
    "cut",
    "dash",
    "daunt",
    "decimate",
    "decry",
    "defame",
    "defraud",
    "deject",
    "demolish",
    "demoralize",
    "denigrate",
    "denounce",
    "denude",
    "deny",
    "deplete",
    "deplore",
    "depopulate",
    "deprecate",
    "depress",
    "deprive",
    "deride",
    "desert",
    "despair",
    "despise",
    "despoil",
    "destroy",
    "detest",
    "devastate",
    "die",
    "dig",
    "disabuse",
    "disappear",
    "disappoint",
    "disapprove",
    "disarm",
    "discombobulate",
    "discomfit",
    "discompose",
    "disconcert",
    "discourage",
    "disdain",
    "disencumber",
    "disgrace",
    "disgruntle",
    "disgust",
    "dishearten",
    "disillusion",
    "dislike",
    "dismay",
    "disown",
    "disparage",
    "dispatch",
    "dispirit",
    "displease",
    "dispossess",
    "disquiet",
    "dissatisfy",
    "distract",
    "distress",
    "distrust",
    "disturb",
    "divest",
    "doubt",
    "drain",
    "dread",
    "drum",
    "ease",
    "electrocute",
    "eliminate",
    "embarass",
    "enrage",
    "envy",
    "exasperate",
    "execrate",
    "execute",
    "exhaust",
    "exonerate",
    "expire",
    "exterminate",
    "extirpate",
    "exult",
    "fault",
    "fear",
    "fine",
    "fire",
    "flabbergast",
    "fleece",
    "flick",
    "fling",
    "flip",
    "flog",
    "fluster",
    "forebode",
    "forfeit",
    "free",
    "fret",
    "frighten",
    "frustrate",
    "fume",
    "garrotte",
    "gloat",
    "grieve",
    "gripe",
    "grouch",
    "grouse",
    "grumble",
    "gull",
    "gush",
    "hammer",
    "hang",
    "harass",
    "hate",
    "haunt",
    "hit",
    "horrify",
    "humiliate",
    "hunger",
    "hurl",
    "hurt",
    "hypnotize",
    "immolate",
    "impeach",
    "infuriate",
    "insult",
    "intimidate",
    "intoxicate",
    "irk",
    "irritate",
    "jab",
    "kick",
    "kill",
    "knife",
    "knock",
    "kvetch",
    "lambaste",
    "lament",
    "lapse",
    "lash",
    "liquidate",
    "loathe",
    "lob",
    "loft",
    "lose",
    "madden",
    "malign",
    "martyr",
    "marvel",
    "massacre",
    "milk",
    "mock",
    "mollify",
    "mope",
    "mortify",
    "mourn",
    "muddle",
    "mulct",
    "murder",
    "nauseate",
    "nudge",
    "object",
    "obliterate",
    "obsess",
    "offend",
    "orphan",
    "outlaw",
    "outrage",
    "overawe",
    "overwhelm",
    "paddle",
    "paddywhack",
    "pain",
    "pardon",
    "pass",
    "pauper",
    "paw",
    "peck",
    "pelt",
    "penalize",
    "perish",
    "perplex",
    "persecute",
    "perturb",
    "pierce",
    "pitch",
    "pity",
    "plague",
    "plunder",
    "poison",
    "poke",
    "pound",
    "preoccupy",
    "prick",
    "prosecute",
    "provoke",
    "pummel",
    "punch",
    "punish",
    "punt",
    "purge",
    "purify",
    "puzzle",
    "rage",
    "ram",
    "rankle",
    "ransack",
    "rap",
    "ravage",
    "rave",
    "raze",
    "rebuke",
    "regret",
    "relieve",
    "relinquish",
    "render",
    "repel",
    "reprimand",
    "reproach",
    "reprove",
    "repulse",
    "resent",
    "revile",
    "revolt",
    "rhapsodize",
    "rid",
    "ridicule",
    "rifle",
    "rob",
    "rue",
    "ruffle",
    "ruin",
    "sacrifice",
    "sadden",
    "salivate",
    "sap",
    "scandalize",
    "scare",
    "scold",
    "scorn",
    "scratch",
    "seethe",
    "shake",
    "shame",
    "shock",
    "shoot",
    "shove",
    "shower",
    "sicken",
    "slam",
    "slap",
    "slaughter",
    "slay",
    "sling",
    "slug",
    "smack",
    "smash",
    "smother",
    "snub",
    "sock",
    "sorrow",
    "spank",
    "spook",
    "stab",
    "stagger",
    "stick",
    "sting",
    "stir",
    "stone",
    "strangle",
    "strap",
    "strike",
    "strip",
    "stump",
    "stun",
    "stupefy",
    "suffer",
    "surrender",
    "suspect",
    "swat",
    "swindle",
    "swipe",
    "tamp",
    "tantalize",
    "tap",
    "tease",
    "terrify",
    "terrorize",
    "thrash",
    "threaten",
    "thrill",
    "throw",
    "thud",
    "thump",
    "thwack",
    "tip",
    "tire",
    "torment",
    "toss",
    "trouble",
    "truncheon",
    "try",
    "unburden",
    "unnerve",
    "unsettle",
    "upbraid",
    "uplift",
    "upset",
    "vanish",
    "vaunt",
    "vex",
    "victimize",
    "vilify",
    "void",
    "wallop",
    "waste",
    "wean",
    "weary",
    "weep",
    "whack",
    "whip",
    "whisk",
    "widow",
    "wonder",
    "worry",
    "wound",
    "wreck"
]

gain_verbs = [
    "accept",
    "accumulate",
    "acquire",
    "appropriate",
    "book",
    "borrow",
    "buy",
    "cadge",
    "call",
    "cash",
    "catch",
    "charter",
    "choose",
    "collect",
    "earn",
    "exact",
    "fetch",
    "find",
    "gain",
    "gather",
    "get",
    "grab",
    "hire",
    "inherit",
    "keep",
    "leave",
    "obtain",
    "order",
    "phone",
    "pick",
    "pluck",
    "procure",
    "pull",
    "reach",
    "receive",
    "recover",
    "regain",
    "reserve",
    "retrieve",
    "save",
    "secure",
    "seize",
    "select",
    "shoot",
    "slaughter",
    "snatch",
    "steal",
    "vote",
    "win"
]

perform_verbs = [
   "abduct",
   "absolve",
   "abstract",
   "acquit",
   "add",
   "annihilate",
   "appraise",
   "arrange",
   "ask",
   "assassinate",
   "assess",
   "balk",
   "banish",
   "bereave",
   "bilk",
   "bleed",
   "blitz",
   "book",
   "borrow",
   "bring",
   "burgle",
   "butcher",
   "buy",
   "cable",
   "cadge",
   "call",
   "cancel",
   "capture",
   "cash",
   "catch",
   "charter",
   "cheat",
   "check",
   "choose",
   "claim",
   "cleanse",
   "click",
   "collect",
   "con",
   "confirm",
   "confiscate",
   "connect",
   "connect",
   "consider",
   "contact",
   "contain",
   "contains",
   "cop",
   "copy",
   "copy-and-paste",
   "cull",
   "cure",
   "decimate",
   "defraud",
   "delete",
   "deliver",
   "demolish",
   "denude",
   "deplete",
   "depopulate",
   "deport",
   "deprive",
   "despoil",
   "destroy",
   "devastate",
   "disabuse",
   "disarm",
   "discharge",
   "disencumber",
   "disengage",
   "disgorge",
   "dislodge",
   "dismiss",
   "dispatch",
   "dispossess",
   "divest",
   "download",
   "drain",
   "draw",
   "e-mail",
   "ease",
   "eject",
   "eliminate",
   "emancipate",
   "embezzle",
   "eradicate",
   "estimate",
   "evacuate",
   "evict",
   "examine",
   "excise",
   "excommunicate",
   "execute",
   "exonerate",
   "exorcise",
   "expel",
   "exterminate",
   "extirpate",
   "extort",
   "extract",
   "extradite",
   "extrude",
   "eye",
   "fax",
   "fetch",
   "filch",
   "find",
   "fix",
   "fleece",
   "flog",
   "free",
   "get",
   "glimpse",
   "grab",
   "gull",
   "help",
   "highlight",
   "immerse",
   "immolate",
   "impound",
   "inspect",
   "install",
   "investigate",
   "join",
   "kidnap",
   "kill",
   "liberate",
   "lift",
   "link",
   "liquidate",
   "lodge",
   "look",
   "lop",
   "massacre",
   "milk",
   "modem",
   "mount",
   "mulct",
   "murder",
   "nab",
   "netmail",
   "network",
   "note",
   "notify",
   "obliterate",
   "observe",
   "omit",
   "open",
   "order",
   "ostracize",
   "oust",
   "overhear",
   "pardon",
   "partition",
   "paste",
   "pay",
   "peg",
   "perceive",
   "phone",
   "pilfer",
   "pinch",
   "pirate",
   "place",
   "plagiarize",
   "plunder",
   "position",
   "price",
   "provide",
   "pry",
   "purchase",
   "purge",
   "purify",
   "purloin",
   "put",
   "radio",
   "ransack",
   "rate",
   "ravage",
   "raze",
   "read",
   "reap",
   "recall",
   "receive",
   "reclaim",
   "recover",
   "redeem",
   "refer",
   "regain",
   "register",
   "relay",
   "relieve",
   "remove",
   "render",
   "reply",
   "repossess",
   "request",
   "rescue",
   "reserve",
   "reset",
   "respond",
   "retreive",
   "retrieve",
   "review",
   "rid",
   "rifle",
   "rob",
   "rsvp",
   "ruin",
   "rustle",
   "sap",
   "satellite",
   "savor",
   "scan",
   "scent",
   "scrutinize",
   "see",
   "seize",
   "select",
   "semaphore",
   "send",
   "separate",
   "set",
   "sever",
   "share",
   "shoo",
   "sign",
   "signal",
   "situate",
   "slaughter",
   "slay",
   "sling",
   "smuggle",
   "snatch",
   "sneak",
   "sponge",
   "start",
   "stash",
   "steal",
   "stow",
   "strip",
   "study",
   "submit",
   "subscribe",
   "subtract",
   "support",
   "survey",
   "swindle",
   "swipe",
   "take",
   "telecast",
   "telegraph",
   "telephone",
   "telex",
   "tell",
   "test",
   "text",
   "thieve",
   "try",
   "type",
   "unburden",
   "unsubscribe",
   "update",
   "uproot",
   "value",
   "verify",
   "view",
   "visit",
   "void",
   "vote",
   "wangle",
   "waste",
   "watch",
   "wean",
   "weasel",
   "winkle",
   "wire",
   "wireless",
   "withdraw",
   "witness",
   "wreck",
   "wrench",
   "wrest"
]

give_verbs = [
    "administer",
    "advance",
    "airmail",
    "allocate",
    "allot",
    "assign",
    "award",
    "bequeath",
    "cede",
    "concede",
    "contribute",
    "convey",
    "covet",
    "crave",
    "credit",
    "deliver",
    "desire",
    "disburse",
    "dispatch",
    "distribute",
    "donate",
    "entrust",
    "express",
    "extend",
    "fancy",
    "fedex",
    "feed",
    "forfeit",
    "forward",
    "furnish",
    "give",
    "grant",
    "guarantee",
    "hand",
    "issue",
    "leave",
    "lend",
    "loan",
    "mail",
    "need",
    "offer",
    "owe",
    "pass",
    "pay",
    "peddle",
    "port",
    "post",
    "present",
    "proffer",
    "promise",
    "provide",
    "refer",
    "refund",
    "reimburse",
    "relinquish",
    "remit",
    "render",
    "rent",
    "repay",
    "restore",
    "return",
    "sacrifice",
    "send",
    "serve",
    "shift",
    "ship",
    "shunt",
    "slip",
    "smuggle",
    "sneak",
    "submit",
    "supply",
    "surrender",
    "transfer",
    "transport",
    "trust",
    "ups",
    "vote",
    "want",
    "will",
    "yield"
]

sashank_categories = {
   "finance":[
      "money",
      "cash",
      "bit coin",
      "bitcoin",
      "cheque",
      "euro",
      "euros",
      "dollar",
      "dollars",
      "rupee",
      "rupees",
      "riyal",
      "riyals",
      "$",
      "£",
      "€",
      "₹",
      "bank",
      "account",
      "transaction",
      "payment",
      "credit card",
      "insurance",
      "transaction",
      "tax",
      "claims",
      "irs",
      "fund",
      "account number",
      "account no",
      "direct deposit",
      "deposit",
      "beneficiary"
   ],
   "personal":[
      "email",
      "e-mail",
      "phone",
      "office address",
      "phone number",
      "contact info",
      "contact information",
      "personal",
      "photo",
      "mobile number",
      "mobile no",
      "phone no",
      "mobile num",
      "phone num",
      "social network",
      "twitter",
      "facebook",
      "social media",
      "volunteer",
      "leave",
      "vacation",
      "sabbatical",
      "training",
      "training notice",
      "notice period",
      "resignation",
      "quit",
      "work from home",
      "family leave",
      "temporary work",
      "temporary work assignment",
      "sick leave",
      "ssn",
      "social security",
      "birthday",
      "citizenship",
      "originally from",
      "home address",
      "address",
      "signature",
      "date of birth",
      "birth date",
      "day of birth"
   ],
   "business":[
      "proposal",
      "proposition",
      "offer",
      "investment",
      "collaboration",
      "partnership",
      "collusion",
      "business"
   ],
   "credentials":[
      "credentials",
      "password",
      "account",
      "slack id",
      "email id",
      "id",
      "user id",
      "login",
      "slack"
   ],
   "privileged_information":[
      "report",
      "document",
      "attachment",
      "files",
      "intellectual property",
      "brochure",
      "code",
      "form",
      "file",
      "software",
      "project",
      "dropbox",
      "github",
      "google drive",
      "gdrive",
      "excel",
      "word document",
      "word",
      "word doc",
      "doc",
      "slides",
      "presentation",
      "contract",
      "wiki",
      "gitlab",
      "ased",
      "testbed",
      "eval",
      "irb",
      "tased",
      "phishing project"
   ],
   "ideology":[
      "human rights",
      "jesus",
      "campaign",
      "health",
      "refugee",
      "humanitarian",
      "climate change",
      "cancer",
      "environment",
      "climate",
      "global warming",
      "autism",
      "activist",
      "charity",
      "donation",
      "flyer",
      "event",
      "celebration",
      "awareness",
      "migrant",
      "pet",
      "dog",
      "cat",
      "animal",
      "event",
      "donate",
      "election",
      "disaster",
      "relief",
      "shooting",
      "gun control",
      "gun control",
      "guns",
      "child relief",
      "migrants",
      "children",
      "border security",
      "bushfires",
      "bush fire",
      "bushfire"
   ],
   "scam":[
      "lottery",
      "lucky draw",
      "winner",
      "prize",
      "award",
      "job",
      "hiring",
      "work experience",
      "interview",
      "candidate",
      "indeed",
      "glassdoor",
      "linkedin",
      "LinkedIn",
      "hackerrank",
      "leetcode",
      "triplebyte",
      "recruiter",
      "start up",
      "startup",
      "workday",
      "work day",
      "recruiting",
      "job profile",
      "gift",
      "present",
      "gift card",
      "gifts card",
      "shop",
      "store"
   ],
   "phishing":[
      "link",
      "click here",
      "download",
      "join us",
      "upload here",
      "apply",
      "apply here",
      "surveymonkey",
      "survey monkey",
      "survey gizmo",
      "surveygizmo",
      "doodle",
      "surveyshare",
      "survey",
      "eventbrite",
      "event brite",
      "workday"
   ]
}

panacea_ask_types = {
  "LOSE": [ #verbs may need to be used differently in their passive (victim in subject) vs active form (victim in DO) for this class but not focused on that for now
    "10.5.pan Lose related Verbs",
    "10.5 Verbs of Possessional Deprivation : Steal Verbs", # <--- don't include this!!
    "10.6.a Verbs of Possessional Deprivation : Cheat Verbs / -of",
    "10.6.c Verbs of Possessional Deprivation : Cheat Verbs / -out of",
    "17.1 Throw Verbs",
    "17.2.i.pan Pelt Verbs",
    "17.2.ii Pelt Verbs -- stone",
    "18.1.a Hit Verbs - Change of State / -with",
    "18.1.b Hit Verbs - Change of State",
    "18.1.c Hit Verbs  - Locational / -at/with",
    "18.1.d Hit Verbs  - Locational / against",
    "18.1.e Hit Verbs  - Change of State / together",
    "18.2.a Swat Verbs",
    "18.2.b Swat Verbs  - Locational",
    "18.3 Spank Verbs",
    "18.4.a Nonagentive Verbs of Impact by Contact - Locational",
    "18.4.b Nonagentive Verbs of Impact by Contact - Change of State",
    "19.a.i Poke Verbs",
    "19.a.ii Poke Verbs - Change of State",
    "19.b Poke Verbs - Locational / -through",
    "19.c.i Poke Verbs / -with",
    "19.c.ii Poke Verbs - Change of State / -with",
    "19.d Poke Verbs - Locational / -with",
    "29.7.pan Orphan Verbs",
    "29.8.a.pan Captain Verbs / Beneficiary",
    "31.1.a.pan Amuse Verbs / -with",
    "31.3.c.pan Marvel Verbs / -for",
    "31.3.f.pan Marvel Verbs / -of",
    "31.3.h.pan Marvel Verbs / -over",
    "33.b Judgment Verbs - Negative / -for/as",
    "37.8.a Complain Verbs / -that/to",
    "37.8.b.pan Complain Verbs / -about/to",
    "42.1.a Murder Verbs - Kill",
    "42.1.c Murder Verbs - General",
    "42.2 Poison Verbs",
    "44.a Destroy Verbs / -with",
    "48.2 Verbs of Disappearance",
    "51.2 Leave Verbs"
    #10.5.p was constructed as follows: (1) Included some verbs from 29.5.b Conjecture ([doubt, suspect, forebode]); (2) Included some verbs from 29.7 Orphan (cripple martyr orphan outlaw); (3) Added (butcher bully), (lose disown deny forfeit relinquish sacrifice surrender ache hurt suffer grieve anguish mourn) from other categories, such as from "13.2", "31.3.d" etc; (4) Included some verbs from 10.5.
    #added these to Steal verbs class for now: "29.5.b Conjecture Verbs / -that", #only some of these verbs ([doubt, suspect, forebode]) but not all! -- Now these appear in 10.5.p Panacea Lose related Verbs (after further changes)
    #added (cripple martyr orphan outlaw) from "29.7 Orphan Verbs" to "10.5 Verbs of Possessional Deprivation : Steal Verbs" -- Now these appear in 10.5.p Panacea Lose related Verbs (after further changes)
    #added (butcher bully), (lose disown deny forfeit relinquish sacrifice surrender ache hurt suffer grieve anguish mourn) from other categories, such as from "13.2", "31.3.d" etc -- Now these appear in 10.5.p Panacea Lose related Verbs (after further changes)
    #moved additionally added verbs in 10.5 to a new category called "10.5.1.a Panacea Lose related Verbs" -- Now the category is called 10.5.p Panacea Lose related Verbs (after further changes)
  ],
  "GAIN": [
    "13.5.1.a Get - No Exchange",
    "13.5.1.b.ii Get - Exchange",
    "13.5.2.a Obtain - No Exchange (CAUSE)",
    "13.5.2.b Obtain - No Exchange (LET w/ benefactive)",
    "13.5.2.c Obtain - No Exchange (LET w/out benefactive)"
  ],
  "GIVE": [
    "11.1 Send Verbs",
    "13.1.a.i Give - No Exchange - Sort of Atelic",
    "13.1.a.ii Give - No Exchange",
    "13.2 Contribute Verbs",
    "13.3 Verbs of Future Having",
    "13.4.1.a Verbs of Fulfilling - Possessional / -to",
    "13.4.1.b Verbs of Fulfilling - Change of State / -with",
    "32.1 Want Verbs"
  ],
  "PERFORM": [
    "9.1 Put Verbs",
    "10.1 Remove Verbs",
    "10.2.b Banish Verbs / -to",
    "10.5 Verbs of Possessional Deprivation : Steal Verbs",
    "10.6.a Verbs of Possessional Deprivation : Cheat Verbs / -of",
    "10.6.c Verbs of Possessional Deprivation : Cheat Verbs / -out of",
    "11.3 Bring and Take Verbs",
    "13.5.1.a.pan Get - No Exchange",
    "13.5.1.b.ii.pan Get - Exchange",
    "13.5.2.d Obtain - Exchange",
    "13.5.2.a.pan Obtain - No Exchange (CAUSE)",
    "22.1.a Mix Verbs - Change of State / -together",
    "29.2.c.pan Characterize Verbs / -as",
    "30.2.a.i.pan Sight Verbs / Bare NP",
    "37.1.e Verbs of Transfer of a Message / -that/to",
    "37.2.a Tell Verbs",
    "37.2.b Tell Verbs / -of/about",
    "37.2.d Tell Verbs / -that/to",
    "37.4.a Verbs of Instrument of Communication",
    "42.1.a Murder Verbs - Kill",
    "42.1.b Murder Verbs - Kill / -with",
    "42.1.c Murder Verbs - General",
    "44.a Destroy Verbs / -with",
    "44.b Destroy Verbs / Instrument Subject",
    "54.4 Price Verbs"
  ],
  "OTHER": []
}
