v_alternates = {
   "abrade":[
      "abrade",
      "abrase"
   ],
   "abrase":[
      "abrade",
      "abrase"
   ],
   "accent":[
      "accent",
      "accentuate"
   ],
   "accentuate":[
      "accent",
      "accentuate"
   ],
   "access":[
      "access",
      "accession"
   ],
   "accession":[
      "access",
      "accession"
   ],
   "acclimatise":[
      "acclimatise",
      "acclimatize"
   ],
   "acclimatize":[
      "acclimatise",
      "acclimatize"
   ],
   "acetylate":[
      "acetylate",
      "acetylize"
   ],
   "acetylize":[
      "acetylate",
      "acetylize"
   ],
   "achromatise":[
      "achromatise",
      "achromatize"
   ],
   "achromatize":[
      "achromatise",
      "achromatize"
   ],
   "actualise":[
      "actualise",
      "actualize"
   ],
   "actualize":[
      "actualise",
      "actualize"
   ],
   "adduce":[
      "adduce",
      "adduct"
   ],
   "adduct":[
      "adduce",
      "adduct"
   ],
   "administer":[
      "administer",
      "administrate"
   ],
   "administrate":[
      "administer",
      "administrate"
   ],
   "advert":[
      "advert",
      "advertize"
   ],
   "advertize":[
      "advert",
      "advertize"
   ],
   "africanise":[
      "africanise",
      "africanize"
   ],
   "africanize":[
      "africanise",
      "africanize"
   ],
   "afrikanerise":[
      "afrikanerise",
      "afrikanerize"
   ],
   "afrikanerize":[
      "afrikanerise",
      "afrikanerize"
   ],
   "aggrandise":[
      "aggrandise",
      "aggrandize"
   ],
   "aggrandize":[
      "aggrandise",
      "aggrandize"
   ],
   "alcoholize":[
      "alcoholize",
      "alcoholise"
   ],
   "alcoholise":[
      "alcoholize",
      "alcoholise"
   ],
   "alien":[
      "alien",
      "alienate"
   ],
   "alienate":[
      "alien",
      "alienate"
   ],
   "allegorize":[
      "allegorize",
      "allegorise"
   ],
   "allegorise":[
      "allegorize",
      "allegorise"
   ],
   "allow":[
      "allow",
      "allowance"
   ],
   "allowance":[
      "allow",
      "allowance"
   ],
   "alphabetise":[
      "alphabetise",
      "alphabetize"
   ],
   "alphabetize":[
      "alphabetise",
      "alphabetize"
   ],
   "americanise":[
      "americanise",
      "americanize"
   ],
   "americanize":[
      "americanise",
      "americanize"
   ],
   "analyse":[
      "analyse",
      "analyze"
   ],
   "analyze":[
      "analyse",
      "analyze"
   ],
   "anathematise":[
      "anathematise",
      "anathematize"
   ],
   "anathematize":[
      "anathematise",
      "anathematize"
   ],
   "anatomise":[
      "anatomise",
      "anatomize"
   ],
   "anatomize":[
      "anatomise",
      "anatomize"
   ],
   "anglicise":[
      "anglicise",
      "anglicize"
   ],
   "anglicize":[
      "anglicise",
      "anglicize"
   ],
   "animate":[
      "animate",
      "animize",
      "animalise",
      "animalize"
   ],
   "animize":[
      "animate",
      "animize",
      "animalise",
      "animalize"
   ],
   "animalise":[
      "animate",
      "animize",
      "animalise",
      "animalize"
   ],
   "animalize":[
      "animate",
      "animize",
      "animalise",
      "animalize"
   ],
   "antagonise":[
      "antagonise",
      "antagonize"
   ],
   "antagonize":[
      "antagonise",
      "antagonize"
   ],
   "antique":[
      "antique",
      "antiquate"
   ],
   "antiquate":[
      "antique",
      "antiquate"
   ],
   "apologise":[
      "apologise",
      "apologize"
   ],
   "apologize":[
      "apologise",
      "apologize"
   ],
   "apotheose":[
      "apotheose",
      "apotheosize"
   ],
   "apotheosize":[
      "apotheose",
      "apotheosize"
   ],
   "appal":[
      "appal",
      "appall"
   ],
   "appall":[
      "appal",
      "appall"
   ],
   "apprise":[
      "apprise",
      "apprize"
   ],
   "apprize":[
      "apprise",
      "apprize"
   ],
   "arm":[
      "arm",
      "armor"
   ],
   "armor":[
      "arm",
      "armor"
   ],
   "aromatise":[
      "aromatise",
      "aromatize"
   ],
   "aromatize":[
      "aromatise",
      "aromatize"
   ],
   "arterialise":[
      "arterialise",
      "arterialize"
   ],
   "arterialize":[
      "arterialise",
      "arterialize"
   ],
   "aspire":[
      "aspire",
      "aspirate"
   ],
   "aspirate":[
      "aspire",
      "aspirate"
   ],
   "atomise":[
      "atomise",
      "atomize"
   ],
   "atomize":[
      "atomise",
      "atomize"
   ],
   "auction":[
      "auction",
      "auctioneer"
   ],
   "auctioneer":[
      "auction",
      "auctioneer"
   ],
   "audit":[
      "audit",
      "audition"
   ],
   "audition":[
      "audit",
      "audition"
   ],
   "author":[
      "author",
      "authorise",
      "authorize"
   ],
   "authorise":[
      "author",
      "authorise",
      "authorize"
   ],
   "authorize":[
      "author",
      "authorise",
      "authorize"
   ],
   "automate":[
      "automate",
      "automatize"
   ],
   "automatize":[
      "automate",
      "automatize"
   ],
   "ax":[
      "ax",
      "axe"
   ],
   "axe":[
      "ax",
      "axe"
   ],
   "balkanise":[
      "balkanise",
      "balkanize"
   ],
   "balkanize":[
      "balkanise",
      "balkanize"
   ],
   "baptise":[
      "baptise",
      "baptize"
   ],
   "baptize":[
      "baptise",
      "baptize"
   ],
   "bath":[
      "bath",
      "bathe"
   ],
   "bathe":[
      "bath",
      "bathe"
   ],
   "beg":[
      "beg",
      "beggar"
   ],
   "beggar":[
      "beg",
      "beggar"
   ],
   "birl":[
      "birl",
      "birle"
   ],
   "birle":[
      "birl",
      "birle"
   ],
   "birth":[
      "birth",
      "birthe"
   ],
   "birthe":[
      "birth",
      "birthe"
   ],
   "bituminise":[
      "bituminise",
      "bituminize"
   ],
   "bituminize":[
      "bituminise",
      "bituminize"
   ],
   "blink":[
      "blink",
      "blinker"
   ],
   "blinker":[
      "blink",
      "blinker"
   ],
   "blood":[
      "blood",
      "bloody"
   ],
   "bloody":[
      "blood",
      "bloody"
   ],
   "bow":[
      "bow",
      "bower"
   ],
   "bower":[
      "bow",
      "bower"
   ],
   "bowdlerise":[
      "bowdlerise",
      "bowdlerize"
   ],
   "bowdlerize":[
      "bowdlerise",
      "bowdlerize"
   ],
   "breach":[
      "breach",
      "broach"
   ],
   "broach":[
      "breach",
      "broach"
   ],
   "brutalise":[
      "brutalise",
      "brutalize"
   ],
   "brutalize":[
      "brutalise",
      "brutalize"
   ],
   "bunk":[
      "bunk",
      "bunker"
   ],
   "bunker":[
      "bunk",
      "bunker"
   ],
   "bur":[
      "bur",
      "burr"
   ],
   "burr":[
      "bur",
      "burr"
   ],
   "burgle":[
      "burgle",
      "burglarise",
      "burglarize"
   ],
   "burglarise":[
      "burgle",
      "burglarise",
      "burglarize"
   ],
   "burglarize":[
      "burgle",
      "burglarise",
      "burglarize"
   ],
   "bus":[
      "bus",
      "buss"
   ],
   "buss":[
      "bus",
      "buss"
   ],
   "caddy":[
      "caddy",
      "caddie"
   ],
   "caddie":[
      "caddy",
      "caddie"
   ],
   "cane":[
      "cane",
      "canal",
      "canalise",
      "canalize"
   ],
   "canal":[
      "cane",
      "canal",
      "canalise",
      "canalize"
   ],
   "canalise":[
      "cane",
      "canal",
      "canalise",
      "canalize"
   ],
   "canalize":[
      "cane",
      "canal",
      "canalise",
      "canalize"
   ],
   "cannibalise":[
      "cannibalise",
      "cannibalize"
   ],
   "cannibalize":[
      "cannibalise",
      "cannibalize"
   ],
   "canonise":[
      "canonise",
      "canonize"
   ],
   "canonize":[
      "canonise",
      "canonize"
   ],
   "canulate":[
      "canulate",
      "cannulate"
   ],
   "cannulate":[
      "canulate",
      "cannulate"
   ],
   "cap":[
      "cap",
      "caption"
   ],
   "caption":[
      "cap",
      "caption"
   ],
   "carbonate":[
      "carbonate",
      "carbonize"
   ],
   "carbonize":[
      "carbonate",
      "carbonize"
   ],
   "carburet":[
      "carburet",
      "carburise",
      "carburize"
   ],
   "carburise":[
      "carburet",
      "carburise",
      "carburize"
   ],
   "carburize":[
      "carburet",
      "carburise",
      "carburize"
   ],
   "category":[
      "category",
      "categorize",
      "categorise"
   ],
   "categorize":[
      "category",
      "categorize",
      "categorise"
   ],
   "categorise":[
      "category",
      "categorize",
      "categorise"
   ],
   "catheterise":[
      "catheterise",
      "catheterize"
   ],
   "catheterize":[
      "catheterise",
      "catheterize"
   ],
   "catholicise":[
      "catholicise",
      "catholicize"
   ],
   "catholicize":[
      "catholicise",
      "catholicize"
   ],
   "cauterise":[
      "cauterise",
      "cauterize"
   ],
   "cauterize":[
      "cauterise",
      "cauterize"
   ],
   "center":[
      "center",
      "centre",
      "centralize"
   ],
   "centre":[
      "center",
      "centre",
      "centralize"
   ],
   "centralize":[
      "center",
      "centre",
      "centralize"
   ],
   "centrifuge":[
      "centrifuge",
      "centrifugate"
   ],
   "centrifugate":[
      "centrifuge",
      "centrifugate"
   ],
   "certify":[
      "certify",
      "certificate"
   ],
   "certificate":[
      "certify",
      "certificate"
   ],
   "chair":[
      "chair",
      "chairman"
   ],
   "chairman":[
      "chair",
      "chairman"
   ],
   "channel":[
      "channel",
      "channelize"
   ],
   "channelize":[
      "channel",
      "channelize"
   ],
   "chaperon":[
      "chaperon",
      "chaperone"
   ],
   "chaperone":[
      "chaperon",
      "chaperone"
   ],
   "character":[
      "character",
      "characterize"
   ],
   "characterize":[
      "character",
      "characterize"
   ],
   "chasten":[
      "chasten",
      "chastise"
   ],
   "chastise":[
      "chasten",
      "chastise"
   ],
   "check":[
      "check",
      "checker"
   ],
   "checker":[
      "check",
      "checker"
   ],
   "christianise":[
      "christianise",
      "christianize"
   ],
   "christianize":[
      "christianise",
      "christianize"
   ],
   "cicatrise":[
      "cicatrise",
      "cicatrize"
   ],
   "cicatrize":[
      "cicatrise",
      "cicatrize"
   ],
   "cinchonise":[
      "cinchonise",
      "cinchonize"
   ],
   "cinchonize":[
      "cinchonise",
      "cinchonize"
   ],
   "circle":[
      "circle",
      "circularize",
      "circularise"
   ],
   "circularize":[
      "circle",
      "circularize",
      "circularise"
   ],
   "circularise":[
      "circle",
      "circularize",
      "circularise"
   ],
   "citify":[
      "citify",
      "cityfy"
   ],
   "cityfy":[
      "citify",
      "cityfy"
   ],
   "clam":[
      "clam",
      "clamor"
   ],
   "clamor":[
      "clam",
      "clamor"
   ],
   "clang":[
      "clang",
      "clangor"
   ],
   "clangor":[
      "clang",
      "clangor"
   ],
   "clink":[
      "clink",
      "clinker"
   ],
   "clinker":[
      "clink",
      "clinker"
   ],
   "close":[
      "close",
      "closure",
      "cloture"
   ],
   "closure":[
      "close",
      "closure",
      "cloture"
   ],
   "cloture":[
      "close",
      "closure",
      "cloture"
   ],
   "cloud":[
      "cloud",
      "clouded"
   ],
   "clouded":[
      "cloud",
      "clouded"
   ],
   "cocainise":[
      "cocainise",
      "cocainize"
   ],
   "cocainize":[
      "cocainise",
      "cocainize"
   ],
   "cock":[
      "cock",
      "cocker"
   ],
   "cocker":[
      "cock",
      "cocker"
   ],
   "cocknify":[
      "cocknify",
      "cockneyfy"
   ],
   "cockneyfy":[
      "cocknify",
      "cockneyfy"
   ],
   "collectivise":[
      "collectivise",
      "collectivize"
   ],
   "collectivize":[
      "collectivise",
      "collectivize"
   ],
   "color":[
      "color",
      "colorate"
   ],
   "colorate":[
      "color",
      "colorate"
   ],
   "comfort":[
      "comfort",
      "comfortable"
   ],
   "comfortable":[
      "comfort",
      "comfortable"
   ],
   "command":[
      "command",
      "commandeer"
   ],
   "commandeer":[
      "command",
      "commandeer"
   ],
   "comment":[
      "comment",
      "commentate"
   ],
   "commentate":[
      "comment",
      "commentate"
   ],
   "commercialise":[
      "commercialise",
      "commercialize"
   ],
   "commercialize":[
      "commercialise",
      "commercialize"
   ],
   "commit":[
      "commit",
      "commission"
   ],
   "commission":[
      "commit",
      "commission"
   ],
   "commune":[
      "commune",
      "communalise",
      "communalize"
   ],
   "communalise":[
      "commune",
      "communalise",
      "communalize"
   ],
   "communalize":[
      "commune",
      "communalise",
      "communalize"
   ],
   "commute":[
      "commute",
      "commutate"
   ],
   "commutate":[
      "commute",
      "commutate"
   ],
   "compartmentalise":[
      "compartmentalise",
      "compartmentalize"
   ],
   "compartmentalize":[
      "compartmentalise",
      "compartmentalize"
   ],
   "compass":[
      "compass",
      "compassionate"
   ],
   "compassionate":[
      "compass",
      "compassionate"
   ],
   "compel":[
      "compel",
      "compell"
   ],
   "compell":[
      "compel",
      "compell"
   ],
   "computerise":[
      "computerise",
      "computerize"
   ],
   "computerize":[
      "computerise",
      "computerize"
   ],
   "conceptualise":[
      "conceptualise",
      "conceptualize"
   ],
   "conceptualize":[
      "conceptualise",
      "conceptualize"
   ],
   "concert":[
      "concert",
      "concertize"
   ],
   "concertize":[
      "concert",
      "concertize"
   ],
   "concrete":[
      "concrete",
      "concretize"
   ],
   "concretize":[
      "concrete",
      "concretize"
   ],
   "concrn":[
      "concrn",
      "concern"
   ],
   "concern":[
      "concrn",
      "concern"
   ],
   "condense":[
      "condense",
      "condensate"
   ],
   "condensate":[
      "condense",
      "condensate"
   ],
   "confect":[
      "confect",
      "confection"
   ],
   "confection":[
      "confect",
      "confection"
   ],
   "conglobe":[
      "conglobe",
      "conglobate"
   ],
   "conglobate":[
      "conglobe",
      "conglobate"
   ],
   "construct":[
      "construct",
      "structure",
      "structuralize"
   ],
   "structure":[
      "construct",
      "structure",
      "structuralize"
   ],
   "structuralize":[
      "construct",
      "structure",
      "structuralize"
   ],
   "containerise":[
      "containerise",
      "containerize"
   ],
   "containerize":[
      "containerise",
      "containerize"
   ],
   "contend":[
      "contend",
      "content"
   ],
   "content":[
      "contend",
      "content"
   ],
   "conventionalise":[
      "conventionalise",
      "conventionalize"
   ],
   "conventionalize":[
      "conventionalise",
      "conventionalize"
   ],
   "convict":[
      "convict",
      "convince"
   ],
   "convince":[
      "convict",
      "convince"
   ],
   "convolve":[
      "convolve",
      "convolute"
   ],
   "convolute":[
      "convolve",
      "convolute"
   ],
   "cooper":[
      "cooper",
      "cooperate",
      "co-operate"
   ],
   "cooperate":[
      "cooper",
      "cooperate",
      "co-operate"
   ],
   "co-operate":[
      "cooper",
      "cooperate",
      "co-operate"
   ],
   "coopt":[
      "coopt",
      "co-opt"
   ],
   "co-opt":[
      "coopt",
      "co-opt"
   ],
   "coordinate":[
      "coordinate",
      "co-ordinate"
   ],
   "co-ordinate":[
      "coordinate",
      "co-ordinate"
   ],
   "copolymerise":[
      "copolymerise",
      "copolymerize"
   ],
   "copolymerize":[
      "copolymerise",
      "copolymerize"
   ],
   "count":[
      "count",
      "counter"
   ],
   "counter":[
      "count",
      "counter"
   ],
   "country":[
      "country",
      "countrify"
   ],
   "countrify":[
      "country",
      "countrify"
   ],
   "crate":[
      "crate",
      "crater"
   ],
   "crater":[
      "crate",
      "crater"
   ],
   "crenel":[
      "crenel",
      "crenelate",
      "crenellate"
   ],
   "crenelate":[
      "crenel",
      "crenelate",
      "crenellate"
   ],
   "crenellate":[
      "crenel",
      "crenelate",
      "crenellate"
   ],
   "criminate":[
      "criminate",
      "criminalize"
   ],
   "criminalize":[
      "criminate",
      "criminalize"
   ],
   "critique":[
      "critique",
      "criticise",
      "criticize"
   ],
   "criticise":[
      "critique",
      "criticise",
      "criticize"
   ],
   "criticize":[
      "critique",
      "criticise",
      "criticize"
   ],
   "crystalize":[
      "crystalize",
      "crystallize"
   ],
   "crystallize":[
      "crystalize",
      "crystallize"
   ],
   "curarise":[
      "curarise",
      "curarize"
   ],
   "curarize":[
      "curarise",
      "curarize"
   ],
   "cutinise":[
      "cutinise",
      "cutinize"
   ],
   "cutinize":[
      "cutinise",
      "cutinize"
   ],
   "deaminate":[
      "deaminate",
      "deaminize"
   ],
   "deaminize":[
      "deaminate",
      "deaminize"
   ],
   "debit":[
      "debit",
      "debite"
   ],
   "debite":[
      "debit",
      "debite"
   ],
   "decarbonate":[
      "decarbonate",
      "decarbonise",
      "decarbonize"
   ],
   "decarbonise":[
      "decarbonate",
      "decarbonise",
      "decarbonize"
   ],
   "decarbonize":[
      "decarbonate",
      "decarbonise",
      "decarbonize"
   ],
   "decarburise":[
      "decarburise",
      "decarburize"
   ],
   "decarburize":[
      "decarburise",
      "decarburize"
   ],
   "decimate":[
      "decimate",
      "decimalise",
      "decimalize"
   ],
   "decimalise":[
      "decimate",
      "decimalise",
      "decimalize"
   ],
   "decimalize":[
      "decimate",
      "decimalise",
      "decimalize"
   ],
   "decolor":[
      "decolor",
      "decolour",
      "decolorize"
   ],
   "decolour":[
      "decolor",
      "decolour",
      "decolorize"
   ],
   "decolorize":[
      "decolor",
      "decolour",
      "decolorize"
   ],
   "decree":[
      "decree",
      "decrement"
   ],
   "decrement":[
      "decree",
      "decrement"
   ],
   "deduce":[
      "deduce",
      "deduct"
   ],
   "deduct":[
      "deduce",
      "deduct"
   ],
   "degust":[
      "degust",
      "degustate"
   ],
   "degustate":[
      "degust",
      "degustate"
   ],
   "dehumanise":[
      "dehumanise",
      "dehumanize"
   ],
   "dehumanize":[
      "dehumanise",
      "dehumanize"
   ],
   "dehypnotise":[
      "dehypnotise",
      "dehypnotize"
   ],
   "dehypnotize":[
      "dehypnotise",
      "dehypnotize"
   ],
   "delimit":[
      "delimit",
      "delimitate"
   ],
   "delimitate":[
      "delimit",
      "delimitate"
   ],
   "delocalise":[
      "delocalise",
      "delocalize"
   ],
   "delocalize":[
      "delocalise",
      "delocalize"
   ],
   "demagnetise":[
      "demagnetise",
      "demagnetize"
   ],
   "demagnetize":[
      "demagnetise",
      "demagnetize"
   ],
   "demilitarise":[
      "demilitarise",
      "demilitarize"
   ],
   "demilitarize":[
      "demilitarise",
      "demilitarize"
   ],
   "demobilise":[
      "demobilise",
      "demobilize"
   ],
   "demobilize":[
      "demobilise",
      "demobilize"
   ],
   "democratise":[
      "democratise",
      "democratize"
   ],
   "democratize":[
      "democratise",
      "democratize"
   ],
   "demonetise":[
      "demonetise",
      "demonetize"
   ],
   "demonetize":[
      "demonetise",
      "demonetize"
   ],
   "demoralise":[
      "demoralise",
      "demoralize"
   ],
   "demoralize":[
      "demoralise",
      "demoralize"
   ],
   "demythologise":[
      "demythologise",
      "demythologize"
   ],
   "demythologize":[
      "demythologise",
      "demythologize"
   ],
   "denationalise":[
      "denationalise",
      "denationalize"
   ],
   "denationalize":[
      "denationalise",
      "denationalize"
   ],
   "denature":[
      "denature",
      "denaturalise",
      "denaturalize"
   ],
   "denaturalise":[
      "denature",
      "denaturalise",
      "denaturalize"
   ],
   "denaturalize":[
      "denature",
      "denaturalise",
      "denaturalize"
   ],
   "denounce":[
      "denounce",
      "denunciate"
   ],
   "denunciate":[
      "denounce",
      "denunciate"
   ],
   "denude":[
      "denude",
      "denudate"
   ],
   "denudate":[
      "denude",
      "denudate"
   ],
   "deodorise":[
      "deodorise",
      "deodorize"
   ],
   "deodorize":[
      "deodorise",
      "deodorize"
   ],
   "deoxidise":[
      "deoxidise",
      "deoxidize"
   ],
   "deoxidize":[
      "deoxidise",
      "deoxidize"
   ],
   "departmentalise":[
      "departmentalise",
      "departmentalize"
   ],
   "departmentalize":[
      "departmentalise",
      "departmentalize"
   ],
   "depersonalise":[
      "depersonalise",
      "depersonalize"
   ],
   "depersonalize":[
      "depersonalise",
      "depersonalize"
   ],
   "depict":[
      "depict",
      "depicture"
   ],
   "depicture":[
      "depict",
      "depicture"
   ],
   "deplume":[
      "deplume",
      "deplumate"
   ],
   "deplumate":[
      "deplume",
      "deplumate"
   ],
   "depolarise":[
      "depolarise",
      "depolarize"
   ],
   "depolarize":[
      "depolarise",
      "depolarize"
   ],
   "depose":[
      "depose",
      "deposit"
   ],
   "deposit":[
      "depose",
      "deposit"
   ],
   "depute":[
      "depute",
      "deputize"
   ],
   "deputize":[
      "depute",
      "deputize"
   ],
   "deraign":[
      "deraign",
      "darraign"
   ],
   "darraign":[
      "deraign",
      "darraign"
   ],
   "derat":[
      "derat",
      "derate"
   ],
   "derate":[
      "derat",
      "derate"
   ],
   "desalinate":[
      "desalinate",
      "desalinize"
   ],
   "desalinize":[
      "desalinate",
      "desalinize"
   ],
   "desensitise":[
      "desensitise",
      "desensitize"
   ],
   "desensitize":[
      "desensitise",
      "desensitize"
   ],
   "desexualise":[
      "desexualise",
      "desexualize"
   ],
   "desexualize":[
      "desexualise",
      "desexualize"
   ],
   "design":[
      "design",
      "designate"
   ],
   "designate":[
      "design",
      "designate"
   ],
   "destroy":[
      "destroy",
      "destruct"
   ],
   "destruct":[
      "destroy",
      "destruct"
   ],
   "desulphurise":[
      "desulphurise",
      "desulphurize"
   ],
   "desulphurize":[
      "desulphurise",
      "desulphurize"
   ],
   "determine":[
      "determine",
      "determinate"
   ],
   "determinate":[
      "determine",
      "determinate"
   ],
   "detoxify":[
      "detoxify",
      "detoxicate"
   ],
   "detoxicate":[
      "detoxify",
      "detoxicate"
   ],
   "detribalise":[
      "detribalise",
      "detribalize"
   ],
   "detribalize":[
      "detribalise",
      "detribalize"
   ],
   "devalue":[
      "devalue",
      "devaluate"
   ],
   "devaluate":[
      "devalue",
      "devaluate"
   ],
   "devest":[
      "devest",
      "divest"
   ],
   "divest":[
      "devest",
      "divest"
   ],
   "devil":[
      "devil",
      "devilize"
   ],
   "devilize":[
      "devil",
      "devilize"
   ],
   "devitalise":[
      "devitalise",
      "devitalize"
   ],
   "devitalize":[
      "devitalise",
      "devitalize"
   ],
   "diabolise":[
      "diabolise",
      "diabolize"
   ],
   "diabolize":[
      "diabolise",
      "diabolize"
   ],
   "diazotise":[
      "diazotise",
      "diazotize"
   ],
   "diazotize":[
      "diazotise",
      "diazotize"
   ],
   "differ":[
      "differ",
      "differentiate"
   ],
   "differentiate":[
      "differ",
      "differentiate"
   ],
   "digitate":[
      "digitate",
      "digitize",
      "digitise",
      "digitalise",
      "digitalize"
   ],
   "digitize":[
      "digitate",
      "digitize",
      "digitise",
      "digitalise",
      "digitalize"
   ],
   "digitise":[
      "digitate",
      "digitize",
      "digitise",
      "digitalise",
      "digitalize"
   ],
   "digitalise":[
      "digitate",
      "digitize",
      "digitise",
      "digitalise",
      "digitalize"
   ],
   "digitalize":[
      "digitate",
      "digitize",
      "digitise",
      "digitalise",
      "digitalize"
   ],
   "din":[
      "din",
      "dine"
   ],
   "dine":[
      "din",
      "dine"
   ],
   "ding":[
      "ding",
      "dinge"
   ],
   "dinge":[
      "ding",
      "dinge"
   ],
   "diphthongise":[
      "diphthongise",
      "diphthongize"
   ],
   "diphthongize":[
      "diphthongise",
      "diphthongize"
   ],
   "discolor":[
      "discolor",
      "discolorize"
   ],
   "discolorize":[
      "discolor",
      "discolorize"
   ],
   "disenthral":[
      "disenthral",
      "disenthrall"
   ],
   "disenthrall":[
      "disenthral",
      "disenthrall"
   ],
   "disorient":[
      "disorient",
      "disorientate"
   ],
   "disorientate":[
      "disorient",
      "disorientate"
   ],
   "dissociate":[
      "dissociate",
      "disassociate"
   ],
   "disassociate":[
      "dissociate",
      "disassociate"
   ],
   "distil":[
      "distil",
      "distill"
   ],
   "distill":[
      "distil",
      "distill"
   ],
   "divert":[
      "divert",
      "diverse"
   ],
   "diverse":[
      "divert",
      "diverse"
   ],
   "divine":[
      "divine",
      "divinise",
      "divinize"
   ],
   "divinise":[
      "divine",
      "divinise",
      "divinize"
   ],
   "divinize":[
      "divine",
      "divinise",
      "divinize"
   ],
   "divulge":[
      "divulge",
      "divulgate"
   ],
   "divulgate":[
      "divulge",
      "divulgate"
   ],
   "do":[
      "do",
      "don"
   ],
   "don":[
      "do",
      "don"
   ],
   "dogmatise":[
      "dogmatise",
      "dogmatize"
   ],
   "dogmatize":[
      "dogmatise",
      "dogmatize"
   ],
   "domesticate":[
      "domesticate",
      "domesticize"
   ],
   "domesticize":[
      "domesticate",
      "domesticize"
   ],
   "dominate":[
      "dominate",
      "domineer"
   ],
   "domineer":[
      "dominate",
      "domineer"
   ],
   "drink":[
      "drink",
      "drunken"
   ],
   "drunken":[
      "drink",
      "drunken"
   ],
   "die":[
      "die",
      "dying"
   ],
   "dying":[
      "die",
      "dying"
   ],
   "economise":[
      "economise",
      "economize"
   ],
   "economize":[
      "economise",
      "economize"
   ],
   "editorialise":[
      "editorialise",
      "editorialize"
   ],
   "editorialize":[
      "editorialise",
      "editorialize"
   ],
   "educe":[
      "educe",
      "educate"
   ],
   "educate":[
      "educe",
      "educate"
   ],
   "effeminate":[
      "effeminate",
      "effeminize"
   ],
   "effeminize":[
      "effeminate",
      "effeminize"
   ],
   "elasticate":[
      "elasticate",
      "elasticise",
      "elasticize"
   ],
   "elasticise":[
      "elasticate",
      "elasticise",
      "elasticize"
   ],
   "elasticize":[
      "elasticate",
      "elasticise",
      "elasticize"
   ],
   "eloin":[
      "eloin",
      "eloign"
   ],
   "eloign":[
      "eloin",
      "eloign"
   ],
   "embed":[
      "embed",
      "imbed"
   ],
   "imbed":[
      "embed",
      "imbed"
   ],
   "embold":[
      "embold",
      "embolden"
   ],
   "embolden":[
      "embold",
      "embolden"
   ],
   "embow":[
      "embow",
      "embower"
   ],
   "embower":[
      "embow",
      "embower"
   ],
   "emend":[
      "emend",
      "emendate"
   ],
   "emendate":[
      "emend",
      "emendate"
   ],
   "emotionalise":[
      "emotionalise",
      "emotionalize"
   ],
   "emotionalize":[
      "emotionalise",
      "emotionalize"
   ],
   "encapsulate":[
      "encapsulate",
      "incapsulate"
   ],
   "incapsulate":[
      "encapsulate",
      "incapsulate"
   ],
   "encase":[
      "encase",
      "incase"
   ],
   "incase":[
      "encase",
      "incase"
   ],
   "encrust":[
      "encrust",
      "incrust"
   ],
   "incrust":[
      "encrust",
      "incrust"
   ],
   "encumber":[
      "encumber",
      "incumber"
   ],
   "incumber":[
      "encumber",
      "incumber"
   ],
   "engraft":[
      "engraft",
      "ingraft"
   ],
   "ingraft":[
      "engraft",
      "ingraft"
   ],
   "enrol":[
      "enrol",
      "enroll"
   ],
   "enroll":[
      "enrol",
      "enroll"
   ],
   "enshrine":[
      "enshrine",
      "inshrine"
   ],
   "inshrine":[
      "enshrine",
      "inshrine"
   ],
   "enter":[
      "enter",
      "ingress",
      "entrance"
   ],
   "ingress":[
      "enter",
      "ingress",
      "entrance"
   ],
   "entrance":[
      "enter",
      "ingress",
      "entrance"
   ],
   "enthral":[
      "enthral",
      "enthrall"
   ],
   "enthrall":[
      "enthral",
      "enthrall"
   ],
   "entreat":[
      "entreat",
      "intreat"
   ],
   "intreat":[
      "entreat",
      "intreat"
   ],
   "entrust":[
      "entrust",
      "intrust"
   ],
   "intrust":[
      "entrust",
      "intrust"
   ],
   "entwine":[
      "entwine",
      "entwintwine"
   ],
   "entwintwine":[
      "entwine",
      "entwintwine"
   ],
   "envelop":[
      "envelop",
      "envelope"
   ],
   "envelope":[
      "envelop",
      "envelope"
   ],
   "equal":[
      "equal",
      "equalise",
      "equalize"
   ],
   "equalise":[
      "equal",
      "equalise",
      "equalize"
   ],
   "equalize":[
      "equal",
      "equalise",
      "equalize"
   ],
   "equilibrate":[
      "equilibrate",
      "equilibrize"
   ],
   "equilibrize":[
      "equilibrate",
      "equilibrize"
   ],
   "eruct":[
      "eruct",
      "eructate"
   ],
   "eructate":[
      "eruct",
      "eructate"
   ],
   "eternize":[
      "eternize",
      "eternalize"
   ],
   "eternalize":[
      "eternize",
      "eternalize"
   ],
   "etherise":[
      "etherise",
      "etherize",
      "etherealise",
      "etherealize"
   ],
   "etherize":[
      "etherise",
      "etherize",
      "etherealise",
      "etherealize"
   ],
   "etherealise":[
      "etherise",
      "etherize",
      "etherealise",
      "etherealize"
   ],
   "etherealize":[
      "etherise",
      "etherize",
      "etherealise",
      "etherealize"
   ],
   "evangelise":[
      "evangelise",
      "evangelize"
   ],
   "evangelize":[
      "evangelise",
      "evangelize"
   ],
   "excel":[
      "excel",
      "excell"
   ],
   "excell":[
      "excel",
      "excell"
   ],
   "excide":[
      "excide",
      "excise"
   ],
   "excise":[
      "excide",
      "excise"
   ],
   "exist":[
      "exist",
      "existing"
   ],
   "existing":[
      "exist",
      "existing"
   ],
   "exorcise":[
      "exorcise",
      "exorcize"
   ],
   "exorcize":[
      "exorcise",
      "exorcize"
   ],
   "expedite":[
      "expedite",
      "expedient"
   ],
   "expedient":[
      "expedite",
      "expedient"
   ],
   "expel":[
      "expel",
      "expell"
   ],
   "expell":[
      "expel",
      "expell"
   ],
   "experience":[
      "experience",
      "experiment"
   ],
   "experiment":[
      "experience",
      "experiment"
   ],
   "expose":[
      "expose",
      "exposit"
   ],
   "exposit":[
      "expose",
      "exposit"
   ],
   "extemporise":[
      "extemporise",
      "extemporize",
      "extemporate"
   ],
   "extemporize":[
      "extemporise",
      "extemporize",
      "extemporate"
   ],
   "extemporate":[
      "extemporise",
      "extemporize",
      "extemporate"
   ],
   "exteriorise":[
      "exteriorise",
      "exteriorize",
      "externalise",
      "externalize"
   ],
   "exteriorize":[
      "exteriorise",
      "exteriorize",
      "externalise",
      "externalize"
   ],
   "externalise":[
      "exteriorise",
      "exteriorize",
      "externalise",
      "externalize"
   ],
   "externalize":[
      "exteriorise",
      "exteriorize",
      "externalise",
      "externalize"
   ],
   "extol":[
      "extol",
      "extoll"
   ],
   "extoll":[
      "extol",
      "extoll"
   ],
   "exude":[
      "exude",
      "exudate"
   ],
   "exudate":[
      "exude",
      "exudate"
   ],
   "factor":[
      "factor",
      "factorise",
      "factorize"
   ],
   "factorise":[
      "factor",
      "factorise",
      "factorize"
   ],
   "factorize":[
      "factor",
      "factorise",
      "factorize"
   ],
   "familiarise":[
      "familiarise",
      "familiarize"
   ],
   "familiarize":[
      "familiarise",
      "familiarize"
   ],
   "faradise":[
      "faradise",
      "faradize"
   ],
   "faradize":[
      "faradise",
      "faradize"
   ],
   "federate":[
      "federate",
      "federalise",
      "federalize"
   ],
   "federalise":[
      "federate",
      "federalise",
      "federalize"
   ],
   "federalize":[
      "federate",
      "federalise",
      "federalize"
   ],
   "fell":[
      "fell",
      "fellate"
   ],
   "fellate":[
      "fell",
      "fellate"
   ],
   "feminize":[
      "feminize",
      "feminise"
   ],
   "feminise":[
      "feminize",
      "feminise"
   ],
   "feudalise":[
      "feudalise",
      "feudalize"
   ],
   "feudalize":[
      "feudalise",
      "feudalize"
   ],
   "fictionalise":[
      "fictionalise",
      "fictionalize"
   ],
   "fictionalize":[
      "fictionalise",
      "fictionalize"
   ],
   "filter":[
      "filter",
      "filtrate"
   ],
   "filtrate":[
      "filter",
      "filtrate"
   ],
   "finance":[
      "finance",
      "financier"
   ],
   "financier":[
      "finance",
      "financier"
   ],
   "fine":[
      "fine",
      "finalize"
   ],
   "finalize":[
      "fine",
      "finalize"
   ],
   "fix":[
      "fix",
      "fixate"
   ],
   "fixate":[
      "fix",
      "fixate"
   ],
   "flavor":[
      "flavor",
      "flavour"
   ],
   "flavour":[
      "flavor",
      "flavour"
   ],
   "flick":[
      "flick",
      "flicker"
   ],
   "flicker":[
      "flick",
      "flicker"
   ],
   "fluoridate":[
      "fluoridate",
      "fluoridize"
   ],
   "fluoridize":[
      "fluoridate",
      "fluoridize"
   ],
   "fly":[
      "fly",
      "flee",
      "flight"
   ],
   "flee":[
      "fly",
      "flee",
      "flight"
   ],
   "flight":[
      "fly",
      "flee",
      "flight"
   ],
   "forgive":[
      "forgive",
      "forgiven"
   ],
   "forgiven":[
      "forgive",
      "forgiven"
   ],
   "forjudge":[
      "forjudge",
      "forejudge"
   ],
   "forejudge":[
      "forjudge",
      "forejudge"
   ],
   "form":[
      "form",
      "format"
   ],
   "format":[
      "form",
      "format"
   ],
   "formalise":[
      "formalise",
      "formalize"
   ],
   "formalize":[
      "formalise",
      "formalize"
   ],
   "formularise":[
      "formularise",
      "formularize"
   ],
   "formularize":[
      "formularise",
      "formularize"
   ],
   "formulate":[
      "formulate",
      "formulize"
   ],
   "formulize":[
      "formulate",
      "formulize"
   ],
   "fossilise":[
      "fossilise",
      "fossilize"
   ],
   "fossilize":[
      "fossilise",
      "fossilize"
   ],
   "found":[
      "found",
      "founder"
   ],
   "founder":[
      "found",
      "founder"
   ],
   "fraction":[
      "fraction",
      "fractionate",
      "fractionize",
      "fractionise"
   ],
   "fractionate":[
      "fraction",
      "fractionate",
      "fractionize",
      "fractionise"
   ],
   "fractionize":[
      "fraction",
      "fractionate",
      "fractionize",
      "fractionise"
   ],
   "fractionise":[
      "fraction",
      "fractionate",
      "fractionize",
      "fractionise"
   ],
   "fragment":[
      "fragment",
      "fragmentize"
   ],
   "fragmentize":[
      "fragment",
      "fragmentize"
   ],
   "frame":[
      "frame",
      "frames"
   ],
   "frames":[
      "frame",
      "frames"
   ],
   "fright":[
      "fright",
      "frighten"
   ],
   "frighten":[
      "fright",
      "frighten"
   ],
   "frost":[
      "frost",
      "freeze",
      "freezing"
   ],
   "freeze":[
      "frost",
      "freeze",
      "freezing"
   ],
   "freezing":[
      "frost",
      "freeze",
      "freezing"
   ],
   "fulfil":[
      "fulfil",
      "fulfill"
   ],
   "fulfill":[
      "fulfil",
      "fulfill"
   ],
   "gas":[
      "gas",
      "gasify"
   ],
   "gasify":[
      "gas",
      "gasify"
   ],
   "gall":[
      "gall",
      "gallant"
   ],
   "gallant":[
      "gall",
      "gallant"
   ],
   "galvanise":[
      "galvanise",
      "galvanize"
   ],
   "galvanize":[
      "galvanise",
      "galvanize"
   ],
   "gelatinise":[
      "gelatinise",
      "gelatinize"
   ],
   "gelatinize":[
      "gelatinise",
      "gelatinize"
   ],
   "general":[
      "general",
      "generalize"
   ],
   "generalize":[
      "general",
      "generalize"
   ],
   "geologise":[
      "geologise",
      "geologize"
   ],
   "geologize":[
      "geologise",
      "geologize"
   ],
   "geometrize":[
      "geometrize",
      "geometrise"
   ],
   "geometrise":[
      "geometrize",
      "geometrise"
   ],
   "germanise":[
      "germanise",
      "germanize"
   ],
   "germanize":[
      "germanise",
      "germanize"
   ],
   "gift":[
      "gift",
      "give"
   ],
   "give":[
      "gift",
      "give"
   ],
   "glory":[
      "glory",
      "glorify"
   ],
   "glorify":[
      "glory",
      "glorify"
   ],
   "gold":[
      "gold",
      "golden"
   ],
   "golden":[
      "gold",
      "golden"
   ],
   "grade":[
      "grade",
      "gradate"
   ],
   "gradate":[
      "grade",
      "gradate"
   ],
   "graph":[
      "graph",
      "graphitise",
      "graphitize"
   ],
   "graphitise":[
      "graph",
      "graphitise",
      "graphitize"
   ],
   "graphitize":[
      "graph",
      "graphitise",
      "graphitize"
   ],
   "grip":[
      "grip",
      "gripe"
   ],
   "gripe":[
      "grip",
      "gripe"
   ],
   "gutturalise":[
      "gutturalise",
      "gutturalize"
   ],
   "gutturalize":[
      "gutturalise",
      "gutturalize"
   ],
   "habit":[
      "habit",
      "habituate"
   ],
   "habituate":[
      "habit",
      "habituate"
   ],
   "halt":[
      "halt",
      "halter"
   ],
   "halter":[
      "halt",
      "halter"
   ],
   "hang":[
      "hang",
      "hanging"
   ],
   "hanging":[
      "hang",
      "hanging"
   ],
   "harmonize":[
      "harmonize",
      "harmonise"
   ],
   "harmonise":[
      "harmonize",
      "harmonise"
   ],
   "hebraise":[
      "hebraise",
      "hebraize"
   ],
   "hebraize":[
      "hebraise",
      "hebraize"
   ],
   "hie":[
      "hie",
      "hying"
   ],
   "hying":[
      "hie",
      "hying"
   ],
   "home":[
      "home",
      "homer"
   ],
   "homer":[
      "home",
      "homer"
   ],
   "homogenise":[
      "homogenise",
      "homogenize"
   ],
   "homogenize":[
      "homogenise",
      "homogenize"
   ],
   "homologate":[
      "homologate",
      "homologize"
   ],
   "homologize":[
      "homologate",
      "homologize"
   ],
   "hone":[
      "hone",
      "honor"
   ],
   "honor":[
      "hone",
      "honor"
   ],
   "hum":[
      "hum",
      "humor"
   ],
   "humor":[
      "hum",
      "humor"
   ],
   "humanise":[
      "humanise",
      "humanize"
   ],
   "humanize":[
      "humanise",
      "humanize"
   ],
   "hybridise":[
      "hybridise",
      "hybridize"
   ],
   "hybridize":[
      "hybridise",
      "hybridize"
   ],
   "hydrogenate":[
      "hydrogenate",
      "hydrogenise",
      "hydrogenize"
   ],
   "hydrogenise":[
      "hydrogenate",
      "hydrogenise",
      "hydrogenize"
   ],
   "hydrogenize":[
      "hydrogenate",
      "hydrogenise",
      "hydrogenize"
   ],
   "hydrolyse":[
      "hydrolyse",
      "hydrolyze"
   ],
   "hydrolyze":[
      "hydrolyse",
      "hydrolyze"
   ],
   "hyperbolise":[
      "hyperbolise",
      "hyperbolize"
   ],
   "hyperbolize":[
      "hyperbolise",
      "hyperbolize"
   ],
   "hypersensitise":[
      "hypersensitise",
      "hypersensitize"
   ],
   "hypersensitize":[
      "hypersensitise",
      "hypersensitize"
   ],
   "hyphen":[
      "hyphen",
      "hyphenate",
      "hyphenize"
   ],
   "hyphenate":[
      "hyphen",
      "hyphenate",
      "hyphenize"
   ],
   "hyphenize":[
      "hyphen",
      "hyphenate",
      "hyphenize"
   ],
   "hyposensitise":[
      "hyposensitise",
      "hyposensitize"
   ],
   "hyposensitize":[
      "hyposensitise",
      "hyposensitize"
   ],
   "hypostatise":[
      "hypostatise",
      "hypostatize"
   ],
   "hypostatize":[
      "hypostatise",
      "hypostatize"
   ],
   "hysterectomise":[
      "hysterectomise",
      "hysterectomize"
   ],
   "hysterectomize":[
      "hysterectomise",
      "hysterectomize"
   ],
   "idealise":[
      "idealise",
      "idealize"
   ],
   "idealize":[
      "idealise",
      "idealize"
   ],
   "idolise":[
      "idolise",
      "idolize",
      "idolatrise",
      "idolatrize"
   ],
   "idolize":[
      "idolise",
      "idolize",
      "idolatrise",
      "idolatrize"
   ],
   "idolatrise":[
      "idolise",
      "idolize",
      "idolatrise",
      "idolatrize"
   ],
   "idolatrize":[
      "idolise",
      "idolize",
      "idolatrise",
      "idolatrize"
   ],
   "illegalise":[
      "illegalise",
      "illegalize"
   ],
   "illegalize":[
      "illegalise",
      "illegalize"
   ],
   "illume":[
      "illume",
      "illumine",
      "illuminate"
   ],
   "illumine":[
      "illume",
      "illumine",
      "illuminate"
   ],
   "illuminate":[
      "illume",
      "illumine",
      "illuminate"
   ],
   "image":[
      "image",
      "imagine"
   ],
   "imagine":[
      "image",
      "imagine"
   ],
   "imbrue":[
      "imbrue",
      "imbruembrue"
   ],
   "imbruembrue":[
      "imbrue",
      "imbruembrue"
   ],
   "immix":[
      "immix",
      "immingle"
   ],
   "immingle":[
      "immix",
      "immingle"
   ],
   "immobilise":[
      "immobilise",
      "immobilize"
   ],
   "immobilize":[
      "immobilise",
      "immobilize"
   ],
   "immortalise":[
      "immortalise",
      "immortalize"
   ],
   "immortalize":[
      "immortalise",
      "immortalize"
   ],
   "immunise":[
      "immunise",
      "immunize"
   ],
   "immunize":[
      "immunise",
      "immunize"
   ],
   "impale":[
      "impale",
      "impalempale"
   ],
   "impalempale":[
      "impale",
      "impalempale"
   ],
   "impel":[
      "impel",
      "impulse"
   ],
   "impulse":[
      "impel",
      "impulse"
   ],
   "impersonate":[
      "impersonate",
      "impersonalise",
      "impersonalize"
   ],
   "impersonalise":[
      "impersonate",
      "impersonalise",
      "impersonalize"
   ],
   "impersonalize":[
      "impersonate",
      "impersonalise",
      "impersonalize"
   ],
   "imply":[
      "imply",
      "implicate"
   ],
   "implicate":[
      "imply",
      "implicate"
   ],
   "impoverish":[
      "impoverish",
      "impovempoverish"
   ],
   "impovempoverish":[
      "impoverish",
      "impovempoverish"
   ],
   "indent":[
      "indent",
      "indenture"
   ],
   "indenture":[
      "indent",
      "indenture"
   ],
   "individuate":[
      "individuate",
      "individualise",
      "individualize"
   ],
   "individualise":[
      "individuate",
      "individualise",
      "individualize"
   ],
   "individualize":[
      "individuate",
      "individualise",
      "individualize"
   ],
   "induce":[
      "induce",
      "induct"
   ],
   "induct":[
      "induce",
      "induct"
   ],
   "industrialise":[
      "industrialise",
      "industrialize"
   ],
   "industrialize":[
      "industrialise",
      "industrialize"
   ],
   "initial":[
      "initial",
      "initiate",
      "initialise",
      "initialize"
   ],
   "initiate":[
      "initial",
      "initiate",
      "initialise",
      "initialize"
   ],
   "initialise":[
      "initial",
      "initiate",
      "initialise",
      "initialize"
   ],
   "initialize":[
      "initial",
      "initiate",
      "initialise",
      "initialize"
   ],
   "innerve":[
      "innerve",
      "innervate"
   ],
   "innervate":[
      "innerve",
      "innervate"
   ],
   "instal":[
      "instal",
      "install"
   ],
   "install":[
      "instal",
      "install"
   ],
   "instance":[
      "instance",
      "instantiate"
   ],
   "instantiate":[
      "instance",
      "instantiate"
   ],
   "instil":[
      "instil",
      "instill"
   ],
   "instill":[
      "instil",
      "instill"
   ],
   "institutionalise":[
      "institutionalise",
      "institutionalize"
   ],
   "institutionalize":[
      "institutionalise",
      "institutionalize"
   ],
   "instrument":[
      "instrument",
      "instrumentate"
   ],
   "instrumentate":[
      "instrument",
      "instrumentate"
   ],
   "intellectualise":[
      "intellectualise",
      "intellectualize"
   ],
   "intellectualize":[
      "intellectualise",
      "intellectualize"
   ],
   "intend":[
      "intend",
      "intent"
   ],
   "intent":[
      "intend",
      "intent"
   ],
   "interline":[
      "interline",
      "interlineate"
   ],
   "interlineate":[
      "interline",
      "interlineate"
   ],
   "internalise":[
      "internalise",
      "internalize"
   ],
   "internalize":[
      "internalise",
      "internalize"
   ],
   "international":[
      "international",
      "internationalise",
      "internationalize"
   ],
   "internationalise":[
      "international",
      "internationalise",
      "internationalize"
   ],
   "internationalize":[
      "international",
      "internationalise",
      "internationalize"
   ],
   "intone":[
      "intone",
      "intonate"
   ],
   "intonate":[
      "intone",
      "intonate"
   ],
   "invalid":[
      "invalid",
      "invalidate"
   ],
   "invalidate":[
      "invalid",
      "invalidate"
   ],
   "invert":[
      "invert",
      "inverse"
   ],
   "inverse":[
      "invert",
      "inverse"
   ],
   "invoke":[
      "invoke",
      "invocate"
   ],
   "invocate":[
      "invoke",
      "invocate"
   ],
   "iodise":[
      "iodise",
      "iodize"
   ],
   "iodize":[
      "iodise",
      "iodize"
   ],
   "islamise":[
      "islamise",
      "islamize"
   ],
   "islamize":[
      "islamise",
      "islamize"
   ],
   "isomerise":[
      "isomerise",
      "isomerize"
   ],
   "isomerize":[
      "isomerise",
      "isomerize"
   ],
   "italianise":[
      "italianise",
      "italianize"
   ],
   "italianize":[
      "italianise",
      "italianize"
   ],
   "italicise":[
      "italicise",
      "italicize"
   ],
   "italicize":[
      "italicise",
      "italicize"
   ],
   "itemise":[
      "itemise",
      "itemize"
   ],
   "itemize":[
      "itemise",
      "itemize"
   ],
   "jargon":[
      "jargon",
      "jargonise",
      "jargonize"
   ],
   "jargonise":[
      "jargon",
      "jargonise",
      "jargonize"
   ],
   "jargonize":[
      "jargon",
      "jargonise",
      "jargonize"
   ],
   "jell":[
      "jell",
      "jelly",
      "jellify"
   ],
   "jelly":[
      "jell",
      "jelly",
      "jellify"
   ],
   "jellify":[
      "jell",
      "jelly",
      "jellify"
   ],
   "jostle":[
      "jostle",
      "justle"
   ],
   "justle":[
      "jostle",
      "justle"
   ],
   "journalize":[
      "journalize",
      "journalise"
   ],
   "journalise":[
      "journalize",
      "journalise"
   ],
   "judaise":[
      "judaise",
      "judaize"
   ],
   "judaize":[
      "judaise",
      "judaize"
   ],
   "keratinise":[
      "keratinise",
      "keratinize"
   ],
   "keratinize":[
      "keratinise",
      "keratinize"
   ],
   "kyanise":[
      "kyanise",
      "kyanize"
   ],
   "kyanize":[
      "kyanise",
      "kyanize"
   ],
   "labialise":[
      "labialise",
      "labialize"
   ],
   "labialize":[
      "labialise",
      "labialize"
   ],
   "lade":[
      "lade",
      "laden"
   ],
   "laden":[
      "lade",
      "laden"
   ],
   "laicise":[
      "laicise",
      "laicize"
   ],
   "laicize":[
      "laicise",
      "laicize"
   ],
   "lambast":[
      "lambast",
      "lambaste"
   ],
   "lambaste":[
      "lambast",
      "lambaste"
   ],
   "lay":[
      "lay",
      "layer"
   ],
   "layer":[
      "lay",
      "layer"
   ],
   "leg":[
      "leg",
      "legate"
   ],
   "legate":[
      "leg",
      "legate"
   ],
   "legalise":[
      "legalise",
      "legalize"
   ],
   "legalize":[
      "legalise",
      "legalize"
   ],
   "legitimate":[
      "legitimate",
      "legitimize"
   ],
   "legitimize":[
      "legitimate",
      "legitimize"
   ],
   "legitimatise":[
      "legitimatise",
      "legitimatize"
   ],
   "legitimatize":[
      "legitimatise",
      "legitimatize"
   ],
   "lever":[
      "lever",
      "leverage"
   ],
   "leverage":[
      "lever",
      "leverage"
   ],
   "liberate":[
      "liberate",
      "liberalise",
      "liberalize"
   ],
   "liberalise":[
      "liberate",
      "liberalise",
      "liberalize"
   ],
   "liberalize":[
      "liberate",
      "liberalise",
      "liberalize"
   ],
   "light":[
      "light",
      "lighter",
      "enlighten"
   ],
   "lighter":[
      "light",
      "lighter",
      "enlighten"
   ],
   "enlighten":[
      "light",
      "lighter",
      "enlighten"
   ],
   "lionise":[
      "lionise",
      "lionize"
   ],
   "lionize":[
      "lionise",
      "lionize"
   ],
   "liquefy":[
      "liquefy",
      "liquify",
      "liquidate",
      "liquidize"
   ],
   "liquify":[
      "liquefy",
      "liquify",
      "liquidate",
      "liquidize"
   ],
   "liquidate":[
      "liquefy",
      "liquify",
      "liquidate",
      "liquidize"
   ],
   "liquidize":[
      "liquefy",
      "liquify",
      "liquidate",
      "liquidize"
   ],
   "live":[
      "live",
      "enliven"
   ],
   "enliven":[
      "live",
      "enliven"
   ],
   "loath":[
      "loath",
      "loathe"
   ],
   "loathe":[
      "loath",
      "loathe"
   ],
   "localise":[
      "localise",
      "localize"
   ],
   "localize":[
      "localise",
      "localize"
   ],
   "long":[
      "long",
      "lengthen"
   ],
   "lengthen":[
      "long",
      "lengthen"
   ],
   "macadamise":[
      "macadamise",
      "macadamize"
   ],
   "macadamize":[
      "macadamise",
      "macadamize"
   ],
   "machine":[
      "machine",
      "machinate"
   ],
   "machinate":[
      "machine",
      "machinate"
   ],
   "magnetise":[
      "magnetise",
      "magnetize"
   ],
   "magnetize":[
      "magnetise",
      "magnetize"
   ],
   "marinade":[
      "marinade",
      "marinate"
   ],
   "marinate":[
      "marinade",
      "marinate"
   ],
   "marshal":[
      "marshal",
      "marshaling"
   ],
   "marshaling":[
      "marshal",
      "marshaling"
   ],
   "martyr":[
      "martyr",
      "martyrize"
   ],
   "martyrize":[
      "martyr",
      "martyrize"
   ],
   "mat":[
      "mat",
      "matt"
   ],
   "matt":[
      "mat",
      "matt"
   ],
   "mature":[
      "mature",
      "maturate"
   ],
   "maturate":[
      "mature",
      "maturate"
   ],
   "maximise":[
      "maximise",
      "maximize"
   ],
   "maximize":[
      "maximise",
      "maximize"
   ],
   "mechanise":[
      "mechanise",
      "mechanize"
   ],
   "mechanize":[
      "mechanise",
      "mechanize"
   ],
   "mediate":[
      "mediate",
      "mediatize",
      "mediatise"
   ],
   "mediatize":[
      "mediate",
      "mediatize",
      "mediatise"
   ],
   "mediatise":[
      "mediate",
      "mediatize",
      "mediatise"
   ],
   "memorise":[
      "memorise",
      "memorize",
      "memorialise",
      "memorialize"
   ],
   "memorize":[
      "memorise",
      "memorize",
      "memorialise",
      "memorialize"
   ],
   "memorialise":[
      "memorise",
      "memorize",
      "memorialise",
      "memorialize"
   ],
   "memorialize":[
      "memorise",
      "memorize",
      "memorialise",
      "memorialize"
   ],
   "mercerise":[
      "mercerise",
      "mercerize"
   ],
   "mercerize":[
      "mercerise",
      "mercerize"
   ],
   "mercurate":[
      "mercurate",
      "mercurialize",
      "mercurialise"
   ],
   "mercurialize":[
      "mercurate",
      "mercurialize",
      "mercurialise"
   ],
   "mercurialise":[
      "mercurate",
      "mercurialize",
      "mercurialise"
   ],
   "mesmerise":[
      "mesmerise",
      "mesmerize"
   ],
   "mesmerize":[
      "mesmerise",
      "mesmerize"
   ],
   "metal":[
      "metal",
      "metallize"
   ],
   "metallize":[
      "metal",
      "metallize"
   ],
   "methodise":[
      "methodise",
      "methodize"
   ],
   "methodize":[
      "methodise",
      "methodize"
   ],
   "militarise":[
      "militarise",
      "militarize"
   ],
   "militarize":[
      "militarise",
      "militarize"
   ],
   "mimic":[
      "mimic",
      "mimicker"
   ],
   "mimicker":[
      "mimic",
      "mimicker"
   ],
   "mineralise":[
      "mineralise",
      "mineralize"
   ],
   "mineralize":[
      "mineralise",
      "mineralize"
   ],
   "miniaturise":[
      "miniaturise",
      "miniaturize"
   ],
   "miniaturize":[
      "miniaturise",
      "miniaturize"
   ],
   "minimise":[
      "minimise",
      "minimize"
   ],
   "minimize":[
      "minimise",
      "minimize"
   ],
   "misprise":[
      "misprise",
      "misprize"
   ],
   "misprize":[
      "misprise",
      "misprize"
   ],
   "mobilise":[
      "mobilise",
      "mobilize"
   ],
   "mobilize":[
      "mobilise",
      "mobilize"
   ],
   "modernise":[
      "modernise",
      "modernize"
   ],
   "modernize":[
      "modernise",
      "modernize"
   ],
   "monetise":[
      "monetise",
      "monetize"
   ],
   "monetize":[
      "monetise",
      "monetize"
   ],
   "mongrelise":[
      "mongrelise",
      "mongrelize"
   ],
   "mongrelize":[
      "mongrelise",
      "mongrelize"
   ],
   "monopolise":[
      "monopolise",
      "monopolize"
   ],
   "monopolize":[
      "monopolise",
      "monopolize"
   ],
   "mope":[
      "mope",
      "moped"
   ],
   "moped":[
      "mope",
      "moped"
   ],
   "moralise":[
      "moralise",
      "moralize"
   ],
   "moralize":[
      "moralise",
      "moralize"
   ],
   "motive":[
      "motive",
      "motivate"
   ],
   "motivate":[
      "motive",
      "motivate"
   ],
   "motor":[
      "motor",
      "motorise",
      "motorize"
   ],
   "motorise":[
      "motor",
      "motorise",
      "motorize"
   ],
   "motorize":[
      "motor",
      "motorise",
      "motorize"
   ],
   "mould":[
      "mould",
      "moult"
   ],
   "moult":[
      "mould",
      "moult"
   ],
   "mud":[
      "mud",
      "muddy"
   ],
   "muddy":[
      "mud",
      "muddy"
   ],
   "municipalise":[
      "municipalise",
      "municipalize"
   ],
   "municipalize":[
      "municipalise",
      "municipalize"
   ],
   "mute":[
      "mute",
      "mutate"
   ],
   "mutate":[
      "mute",
      "mutate"
   ],
   "mutualise":[
      "mutualise",
      "mutualize"
   ],
   "mutualize":[
      "mutualise",
      "mutualize"
   ],
   "mythicise":[
      "mythicise",
      "mythicize"
   ],
   "mythicize":[
      "mythicise",
      "mythicize"
   ],
   "mythologise":[
      "mythologise",
      "mythologize"
   ],
   "mythologize":[
      "mythologise",
      "mythologize"
   ],
   "narcotise":[
      "narcotise",
      "narcotize"
   ],
   "narcotize":[
      "narcotise",
      "narcotize"
   ],
   "nasale":[
      "nasale",
      "nasalise",
      "nasalize"
   ],
   "nasalise":[
      "nasale",
      "nasalise",
      "nasalize"
   ],
   "nasalize":[
      "nasale",
      "nasalise",
      "nasalize"
   ],
   "nationalise":[
      "nationalise",
      "nationalize"
   ],
   "nationalize":[
      "nationalise",
      "nationalize"
   ],
   "naturalise":[
      "naturalise",
      "naturalize"
   ],
   "naturalize":[
      "naturalise",
      "naturalize"
   ],
   "nebulise":[
      "nebulise",
      "nebulize"
   ],
   "nebulize":[
      "nebulise",
      "nebulize"
   ],
   "neutralise":[
      "neutralise",
      "neutralize"
   ],
   "neutralize":[
      "neutralise",
      "neutralize"
   ],
   "nictate":[
      "nictate",
      "nictitate"
   ],
   "nictitate":[
      "nictate",
      "nictitate"
   ],
   "nidify":[
      "nidify",
      "nidificate"
   ],
   "nidificate":[
      "nidify",
      "nidificate"
   ],
   "normalise":[
      "normalise",
      "normalize"
   ],
   "normalize":[
      "normalise",
      "normalize"
   ],
   "normanise":[
      "normanise",
      "normanize"
   ],
   "normanize":[
      "normanise",
      "normanize"
   ],
   "note":[
      "note",
      "notate"
   ],
   "notate":[
      "note",
      "notate"
   ],
   "nut":[
      "nut",
      "nutate"
   ],
   "nutate":[
      "nut",
      "nutate"
   ],
   "oblige":[
      "oblige",
      "obligate"
   ],
   "obligate":[
      "oblige",
      "obligate"
   ],
   "occidentalise":[
      "occidentalise",
      "occidentalize"
   ],
   "occidentalize":[
      "occidentalise",
      "occidentalize"
   ],
   "officer":[
      "officer",
      "officiate",
      "officialize"
   ],
   "officiate":[
      "officer",
      "officiate",
      "officialize"
   ],
   "officialize":[
      "officer",
      "officiate",
      "officialize"
   ],
   "ope":[
      "ope",
      "opt"
   ],
   "opt":[
      "ope",
      "opt"
   ],
   "optimise":[
      "optimise",
      "optimize"
   ],
   "optimize":[
      "optimise",
      "optimize"
   ],
   "orient":[
      "orient",
      "orientate",
      "orientalise",
      "orientalize"
   ],
   "orientate":[
      "orient",
      "orientate",
      "orientalise",
      "orientalize"
   ],
   "orientalise":[
      "orient",
      "orientate",
      "orientalise",
      "orientalize"
   ],
   "orientalize":[
      "orient",
      "orientate",
      "orientalise",
      "orientalize"
   ],
   "overcapitalise":[
      "overcapitalise",
      "overcapitalize"
   ],
   "overcapitalize":[
      "overcapitalise",
      "overcapitalize"
   ],
   "oxidate":[
      "oxidate",
      "oxidise",
      "oxidize"
   ],
   "oxidise":[
      "oxidate",
      "oxidise",
      "oxidize"
   ],
   "oxidize":[
      "oxidate",
      "oxidise",
      "oxidize"
   ],
   "oxygenate":[
      "oxygenate",
      "oxygenize"
   ],
   "oxygenize":[
      "oxygenate",
      "oxygenize"
   ],
   "ozonise":[
      "ozonise",
      "ozonize"
   ],
   "ozonize":[
      "ozonise",
      "ozonize"
   ],
   "pack":[
      "pack",
      "package"
   ],
   "package":[
      "pack",
      "package"
   ],
   "paganise":[
      "paganise",
      "paganize"
   ],
   "paganize":[
      "paganise",
      "paganize"
   ],
   "page":[
      "page",
      "paginate"
   ],
   "paginate":[
      "page",
      "paginate"
   ],
   "palatalise":[
      "palatalise",
      "palatalize"
   ],
   "palatalize":[
      "palatalise",
      "palatalize"
   ],
   "parabolize":[
      "parabolize",
      "parabolise"
   ],
   "parabolise":[
      "parabolize",
      "parabolise"
   ],
   "parade":[
      "parade",
      "paradize"
   ],
   "paradize":[
      "parade",
      "paradize"
   ],
   "parallel":[
      "parallel",
      "parallelize"
   ],
   "parallelize":[
      "parallel",
      "parallelize"
   ],
   "paralyse":[
      "paralyse",
      "paralyze"
   ],
   "paralyze":[
      "paralyse",
      "paralyze"
   ],
   "pare":[
      "pare",
      "parent"
   ],
   "parent":[
      "pare",
      "parent"
   ],
   "part":[
      "part",
      "partition"
   ],
   "partition":[
      "part",
      "partition"
   ],
   "particularise":[
      "particularise",
      "particularize"
   ],
   "particularize":[
      "particularise",
      "particularize"
   ],
   "patinate":[
      "patinate",
      "patinize"
   ],
   "patinize":[
      "patinate",
      "patinize"
   ],
   "patronage":[
      "patronage",
      "patronise",
      "patronize"
   ],
   "patronise":[
      "patronage",
      "patronise",
      "patronize"
   ],
   "patronize":[
      "patronage",
      "patronise",
      "patronize"
   ],
   "pauper":[
      "pauper",
      "pauperize"
   ],
   "pauperize":[
      "pauper",
      "pauperize"
   ],
   "pectise":[
      "pectise",
      "pectize"
   ],
   "pectize":[
      "pectise",
      "pectize"
   ],
   "pen":[
      "pen",
      "penance"
   ],
   "penance":[
      "pen",
      "penance"
   ],
   "penalise":[
      "penalise",
      "penalize"
   ],
   "penalize":[
      "penalise",
      "penalize"
   ],
   "peptise":[
      "peptise",
      "peptize"
   ],
   "peptize":[
      "peptise",
      "peptize"
   ],
   "peptonise":[
      "peptonise",
      "peptonize"
   ],
   "peptonize":[
      "peptonise",
      "peptonize"
   ],
   "personate":[
      "personate",
      "personalise",
      "personalize"
   ],
   "personalise":[
      "personate",
      "personalise",
      "personalize"
   ],
   "personalize":[
      "personate",
      "personalise",
      "personalize"
   ],
   "perturb":[
      "perturb",
      "perturbate"
   ],
   "perturbate":[
      "perturb",
      "perturbate"
   ],
   "philosophise":[
      "philosophise",
      "philosophize"
   ],
   "philosophize":[
      "philosophise",
      "philosophize"
   ],
   "phosphatise":[
      "phosphatise",
      "phosphatize"
   ],
   "phosphatize":[
      "phosphatise",
      "phosphatize"
   ],
   "photosensitise":[
      "photosensitise",
      "photosensitize"
   ],
   "photosensitize":[
      "photosensitise",
      "photosensitize"
   ],
   "pig":[
      "pig",
      "pigment"
   ],
   "pigment":[
      "pig",
      "pigment"
   ],
   "plagiarise":[
      "plagiarise",
      "plagiarize"
   ],
   "plagiarize":[
      "plagiarise",
      "plagiarize"
   ],
   "plasticise":[
      "plasticise",
      "plasticize"
   ],
   "plasticize":[
      "plasticise",
      "plasticize"
   ],
   "platinise":[
      "platinise",
      "platinize"
   ],
   "platinize":[
      "platinise",
      "platinize"
   ],
   "please":[
      "please",
      "pleasure"
   ],
   "pleasure":[
      "please",
      "pleasure"
   ],
   "pluralise":[
      "pluralise",
      "pluralize"
   ],
   "pluralize":[
      "pluralise",
      "pluralize"
   ],
   "pole":[
      "pole",
      "polarise",
      "polarize"
   ],
   "polarise":[
      "pole",
      "polarise",
      "polarize"
   ],
   "polarize":[
      "pole",
      "polarise",
      "polarize"
   ],
   "poleax":[
      "poleax",
      "poleaxe"
   ],
   "poleaxe":[
      "poleax",
      "poleaxe"
   ],
   "pollenate":[
      "pollenate",
      "pollinate"
   ],
   "pollinate":[
      "pollenate",
      "pollinate"
   ],
   "polychrome":[
      "polychrome",
      "polychromize"
   ],
   "polychromize":[
      "polychrome",
      "polychromize"
   ],
   "polymerise":[
      "polymerise",
      "polymerize"
   ],
   "polymerize":[
      "polymerise",
      "polymerize"
   ],
   "popularise":[
      "popularise",
      "popularize"
   ],
   "popularize":[
      "popularise",
      "popularize"
   ],
   "port":[
      "port",
      "portion",
      "portend"
   ],
   "portion":[
      "port",
      "portion",
      "portend"
   ],
   "portend":[
      "port",
      "portion",
      "portend"
   ],
   "pose":[
      "pose",
      "posit",
      "position"
   ],
   "posit":[
      "pose",
      "posit",
      "position"
   ],
   "position":[
      "pose",
      "posit",
      "position"
   ],
   "post":[
      "post",
      "poster"
   ],
   "poster":[
      "post",
      "poster"
   ],
   "powder":[
      "powder",
      "powderize"
   ],
   "powderize":[
      "powder",
      "powderize"
   ],
   "practice":[
      "practice",
      "practise"
   ],
   "practise":[
      "practice",
      "practise"
   ],
   "preconise":[
      "preconise",
      "preconize"
   ],
   "preconize":[
      "preconise",
      "preconize"
   ],
   "predestine":[
      "predestine",
      "predestinate"
   ],
   "predestinate":[
      "predestine",
      "predestinate"
   ],
   "premier":[
      "premier",
      "premiere"
   ],
   "premiere":[
      "premier",
      "premiere"
   ],
   "prescribe":[
      "prescribe",
      "prescript"
   ],
   "prescript":[
      "prescribe",
      "prescript"
   ],
   "press":[
      "press",
      "pressure",
      "pressurise",
      "pressurize"
   ],
   "pressure":[
      "press",
      "pressure",
      "pressurise",
      "pressurize"
   ],
   "pressurise":[
      "press",
      "pressure",
      "pressurise",
      "pressurize"
   ],
   "pressurize":[
      "press",
      "pressure",
      "pressurise",
      "pressurize"
   ],
   "pretend":[
      "pretend",
      "pretense"
   ],
   "pretense":[
      "pretend",
      "pretense"
   ],
   "prey":[
      "prey",
      "predate"
   ],
   "predate":[
      "prey",
      "predate"
   ],
   "prim":[
      "prim",
      "prime"
   ],
   "prime":[
      "prim",
      "prime"
   ],
   "proceed":[
      "proceed",
      "process"
   ],
   "process":[
      "proceed",
      "process"
   ],
   "profit":[
      "profit",
      "profiteer"
   ],
   "profiteer":[
      "profit",
      "profiteer"
   ],
   "prolong":[
      "prolong",
      "prolongate"
   ],
   "prolongate":[
      "prolong",
      "prolongate"
   ],
   "pronominalise":[
      "pronominalise",
      "pronominalize"
   ],
   "pronominalize":[
      "pronominalise",
      "pronominalize"
   ],
   "proof":[
      "proof",
      "prove"
   ],
   "prove":[
      "proof",
      "prove"
   ],
   "propel":[
      "propel",
      "propell"
   ],
   "propell":[
      "propel",
      "propell"
   ],
   "proportion":[
      "proportion",
      "proportionate"
   ],
   "proportionate":[
      "proportion",
      "proportionate"
   ],
   "proselyte":[
      "proselyte",
      "proselytise",
      "proselytize"
   ],
   "proselytise":[
      "proselyte",
      "proselytise",
      "proselytize"
   ],
   "proselytize":[
      "proselyte",
      "proselytise",
      "proselytize"
   ],
   "provide":[
      "provide",
      "provision"
   ],
   "provision":[
      "provide",
      "provision"
   ],
   "prussianise":[
      "prussianise",
      "prussianize"
   ],
   "prussianize":[
      "prussianise",
      "prussianize"
   ],
   "publish":[
      "publish",
      "publicise",
      "publicize"
   ],
   "publicise":[
      "publish",
      "publicise",
      "publicize"
   ],
   "publicize":[
      "publish",
      "publicise",
      "publicize"
   ],
   "pulse":[
      "pulse",
      "pulsate"
   ],
   "pulsate":[
      "pulse",
      "pulsate"
   ],
   "pulverise":[
      "pulverise",
      "pulverize"
   ],
   "pulverize":[
      "pulverise",
      "pulverize"
   ],
   "putt":[
      "putt",
      "putter"
   ],
   "putter":[
      "putt",
      "putter"
   ],
   "quadruple":[
      "quadruple",
      "quadruplicate"
   ],
   "quadruplicate":[
      "quadruple",
      "quadruplicate"
   ],
   "quantise":[
      "quantise",
      "quantize"
   ],
   "quantize":[
      "quantise",
      "quantize"
   ],
   "quintuple":[
      "quintuple",
      "quintuplicate"
   ],
   "quintuplicate":[
      "quintuple",
      "quintuplicate"
   ],
   "quiz":[
      "quiz",
      "quizzes"
   ],
   "quizzes":[
      "quiz",
      "quizzes"
   ],
   "racket":[
      "racket",
      "racketeer"
   ],
   "racketeer":[
      "racket",
      "racketeer"
   ],
   "raft":[
      "raft",
      "rafter"
   ],
   "rafter":[
      "raft",
      "rafter"
   ],
   "randomise":[
      "randomise",
      "randomize"
   ],
   "randomize":[
      "randomise",
      "randomize"
   ],
   "ration":[
      "ration",
      "rationalise",
      "rationalize"
   ],
   "rationalise":[
      "ration",
      "rationalise",
      "rationalize"
   ],
   "rationalize":[
      "ration",
      "rationalise",
      "rationalize"
   ],
   "raze":[
      "raze",
      "razor"
   ],
   "razor":[
      "raze",
      "razor"
   ],
   "realise":[
      "realise",
      "realize"
   ],
   "realize":[
      "realise",
      "realize"
   ],
   "recap":[
      "recap",
      "recapitulate"
   ],
   "recapitulate":[
      "recap",
      "recapitulate"
   ],
   "recede":[
      "recede",
      "recess"
   ],
   "recess":[
      "recede",
      "recess"
   ],
   "receipt":[
      "receipt",
      "receive"
   ],
   "receive":[
      "receipt",
      "receive"
   ],
   "recognise":[
      "recognise",
      "recognize"
   ],
   "recognize":[
      "recognise",
      "recognize"
   ],
   "reconnoiter":[
      "reconnoiter",
      "reconnoitre"
   ],
   "reconnoitre":[
      "reconnoiter",
      "reconnoitre"
   ],
   "recrystallise":[
      "recrystallise",
      "recrystallize"
   ],
   "recrystallize":[
      "recrystallise",
      "recrystallize"
   ],
   "recur":[
      "recur",
      "recurse"
   ],
   "recurse":[
      "recur",
      "recurse"
   ],
   "refer":[
      "refer",
      "reference"
   ],
   "reference":[
      "refer",
      "reference"
   ],
   "refine":[
      "refine",
      "refinance"
   ],
   "refinance":[
      "refine",
      "refinance"
   ],
   "register":[
      "register",
      "registrate"
   ],
   "registrate":[
      "register",
      "registrate"
   ],
   "regularise":[
      "regularise",
      "regularize"
   ],
   "regularize":[
      "regularise",
      "regularize"
   ],
   "rejuvenate":[
      "rejuvenate",
      "rejuvenesce"
   ],
   "rejuvenesce":[
      "rejuvenate",
      "rejuvenesce"
   ],
   "rely":[
      "rely",
      "relie"
   ],
   "relie":[
      "rely",
      "relie"
   ],
   "remain":[
      "remain",
      "remainder"
   ],
   "remainder":[
      "remain",
      "remainder"
   ],
   "remonetise":[
      "remonetise",
      "remonetize"
   ],
   "remonetize":[
      "remonetise",
      "remonetize"
   ],
   "rend":[
      "rend",
      "rent"
   ],
   "rent":[
      "rend",
      "rent"
   ],
   "renew":[
      "renew",
      "renewal"
   ],
   "renewal":[
      "renew",
      "renewal"
   ],
   "renounce":[
      "renounce",
      "renunciate"
   ],
   "renunciate":[
      "renounce",
      "renunciate"
   ],
   "reorient":[
      "reorient",
      "reorientate"
   ],
   "reorientate":[
      "reorient",
      "reorientate"
   ],
   "repeat":[
      "repeat",
      "repetition"
   ],
   "repetition":[
      "repeat",
      "repetition"
   ],
   "repel":[
      "repel",
      "repulse"
   ],
   "repulse":[
      "repel",
      "repulse"
   ],
   "reposit":[
      "reposit",
      "reposition"
   ],
   "reposition":[
      "reposit",
      "reposition"
   ],
   "republicanise":[
      "republicanise",
      "republicanize"
   ],
   "republicanize":[
      "republicanise",
      "republicanize"
   ],
   "require":[
      "require",
      "requisition"
   ],
   "requisition":[
      "require",
      "requisition"
   ],
   "resin":[
      "resin",
      "resinate"
   ],
   "resinate":[
      "resin",
      "resinate"
   ],
   "respire":[
      "respire",
      "respirate"
   ],
   "respirate":[
      "respire",
      "respirate"
   ],
   "revalorise":[
      "revalorise",
      "revalorize"
   ],
   "revalorize":[
      "revalorise",
      "revalorize"
   ],
   "revalue":[
      "revalue",
      "revaluate"
   ],
   "revaluate":[
      "revalue",
      "revaluate"
   ],
   "revel":[
      "revel",
      "reveal"
   ],
   "reveal":[
      "revel",
      "reveal"
   ],
   "revere":[
      "revere",
      "reverence"
   ],
   "reverence":[
      "revere",
      "reverence"
   ],
   "revert":[
      "revert",
      "reverse"
   ],
   "reverse":[
      "revert",
      "reverse"
   ],
   "revitalise":[
      "revitalise",
      "revitalize"
   ],
   "revitalize":[
      "revitalise",
      "revitalize"
   ],
   "revolt":[
      "revolt",
      "revolve"
   ],
   "revolve":[
      "revolt",
      "revolve"
   ],
   "rhapsodise":[
      "rhapsodise",
      "rhapsodize"
   ],
   "rhapsodize":[
      "rhapsodise",
      "rhapsodize"
   ],
   "roentgenise":[
      "roentgenise",
      "roentgenize"
   ],
   "roentgenize":[
      "roentgenise",
      "roentgenize"
   ],
   "romanise":[
      "romanise",
      "romanize"
   ],
   "romanize":[
      "romanise",
      "romanize"
   ],
   "romanticise":[
      "romanticise",
      "romanticize"
   ],
   "romanticize":[
      "romanticise",
      "romanticize"
   ],
   "rout":[
      "rout",
      "route"
   ],
   "route":[
      "rout",
      "route"
   ],
   "rubber":[
      "rubber",
      "rubberize"
   ],
   "rubberize":[
      "rubber",
      "rubberize"
   ],
   "rubric":[
      "rubric",
      "rubricate"
   ],
   "rubricate":[
      "rubric",
      "rubricate"
   ],
   "ruin":[
      "ruin",
      "ruinate"
   ],
   "ruinate":[
      "ruin",
      "ruinate"
   ],
   "ruralise":[
      "ruralise",
      "ruralize"
   ],
   "ruralize":[
      "ruralise",
      "ruralize"
   ],
   "russianise":[
      "russianise",
      "russianize"
   ],
   "russianize":[
      "russianise",
      "russianize"
   ],
   "sanitate":[
      "sanitate",
      "sanitise",
      "sanitize"
   ],
   "sanitise":[
      "sanitate",
      "sanitise",
      "sanitize"
   ],
   "sanitize":[
      "sanitate",
      "sanitise",
      "sanitize"
   ],
   "satirise":[
      "satirise",
      "satirize"
   ],
   "satirize":[
      "satirise",
      "satirize"
   ],
   "save":[
      "save",
      "savor"
   ],
   "savor":[
      "save",
      "savor"
   ],
   "scandalise":[
      "scandalise",
      "scandalize"
   ],
   "scandalize":[
      "scandalise",
      "scandalize"
   ],
   "schematize":[
      "schematize",
      "schematise"
   ],
   "schematise":[
      "schematize",
      "schematise"
   ],
   "scrap":[
      "scrap",
      "scrape"
   ],
   "scrape":[
      "scrap",
      "scrape"
   ],
   "scrutinise":[
      "scrutinise",
      "scrutinize"
   ],
   "scrutinize":[
      "scrutinise",
      "scrutinize"
   ],
   "sculpt":[
      "sculpt",
      "sculpture"
   ],
   "sculpture":[
      "sculpt",
      "sculpture"
   ],
   "secern":[
      "secern",
      "secernate"
   ],
   "secernate":[
      "secern",
      "secernate"
   ],
   "section":[
      "section",
      "sectionalise",
      "sectionalize"
   ],
   "sectionalise":[
      "section",
      "sectionalise",
      "sectionalize"
   ],
   "sectionalize":[
      "section",
      "sectionalise",
      "sectionalize"
   ],
   "secularise":[
      "secularise",
      "secularize"
   ],
   "secularize":[
      "secularise",
      "secularize"
   ],
   "see":[
      "see",
      "sight"
   ],
   "sight":[
      "see",
      "sight"
   ],
   "seise":[
      "seise",
      "seize"
   ],
   "seize":[
      "seise",
      "seize"
   ],
   "sense":[
      "sense",
      "sensitise",
      "sensitize"
   ],
   "sensitise":[
      "sense",
      "sensitise",
      "sensitize"
   ],
   "sensitize":[
      "sense",
      "sensitise",
      "sensitize"
   ],
   "sentimentalise":[
      "sentimentalise",
      "sentimentalize"
   ],
   "sentimentalize":[
      "sentimentalise",
      "sentimentalize"
   ],
   "sequester":[
      "sequester",
      "sequestrate"
   ],
   "sequestrate":[
      "sequester",
      "sequestrate"
   ],
   "serialise":[
      "serialise",
      "serialize"
   ],
   "serialize":[
      "serialise",
      "serialize"
   ],
   "serve":[
      "serve",
      "service"
   ],
   "service":[
      "serve",
      "service"
   ],
   "sever":[
      "sever",
      "severalize"
   ],
   "severalize":[
      "sever",
      "severalize"
   ],
   "sherardise":[
      "sherardise",
      "sherardize"
   ],
   "sherardize":[
      "sherardise",
      "sherardize"
   ],
   "shoe":[
      "shoe",
      "shoal"
   ],
   "shoal":[
      "shoe",
      "shoal"
   ],
   "sign":[
      "sign",
      "signal",
      "signalize"
   ],
   "signal":[
      "sign",
      "signal",
      "signalize"
   ],
   "signalize":[
      "sign",
      "signal",
      "signalize"
   ],
   "sing":[
      "sing",
      "singe"
   ],
   "singe":[
      "sing",
      "singe"
   ],
   "singularise":[
      "singularise",
      "singularize"
   ],
   "singularize":[
      "singularise",
      "singularize"
   ],
   "skeletonise":[
      "skeletonise",
      "skeletonize"
   ],
   "skeletonize":[
      "skeletonise",
      "skeletonize"
   ],
   "socialise":[
      "socialise",
      "socialize"
   ],
   "socialize":[
      "socialise",
      "socialize"
   ],
   "solarise":[
      "solarise",
      "solarize"
   ],
   "solarize":[
      "solarise",
      "solarize"
   ],
   "solemnise":[
      "solemnise",
      "solemnize"
   ],
   "solemnize":[
      "solemnise",
      "solemnize"
   ],
   "solve":[
      "solve",
      "solvate"
   ],
   "solvate":[
      "solve",
      "solvate"
   ],
   "sovietise":[
      "sovietise",
      "sovietize"
   ],
   "sovietize":[
      "sovietise",
      "sovietize"
   ],
   "specialise":[
      "specialise",
      "specialize"
   ],
   "specialize":[
      "specialise",
      "specialize"
   ],
   "spirit":[
      "spirit",
      "spiritize",
      "spiritualize",
      "spiritualise"
   ],
   "spiritize":[
      "spirit",
      "spiritize",
      "spiritualize",
      "spiritualise"
   ],
   "spiritualize":[
      "spirit",
      "spiritize",
      "spiritualize",
      "spiritualise"
   ],
   "spiritualise":[
      "spirit",
      "spiritize",
      "spiritualize",
      "spiritualise"
   ],
   "stable":[
      "stable",
      "stabilise",
      "stabilize"
   ],
   "stabilise":[
      "stable",
      "stabilise",
      "stabilize"
   ],
   "stabilize":[
      "stable",
      "stabilise",
      "stabilize"
   ],
   "stand":[
      "stand",
      "station"
   ],
   "station":[
      "stand",
      "station"
   ],
   "standardise":[
      "standardise",
      "standardize"
   ],
   "standardize":[
      "standardise",
      "standardize"
   ],
   "sterilise":[
      "sterilise",
      "sterilize"
   ],
   "sterilize":[
      "sterilise",
      "sterilize"
   ],
   "stigmatise":[
      "stigmatise",
      "stigmatize"
   ],
   "stigmatize":[
      "stigmatise",
      "stigmatize"
   ],
   "strangle":[
      "strangle",
      "strangulate"
   ],
   "strangulate":[
      "strangle",
      "strangulate"
   ],
   "stupefy":[
      "stupefy",
      "stupify"
   ],
   "stupify":[
      "stupefy",
      "stupify"
   ],
   "style":[
      "style",
      "stylise",
      "stylize"
   ],
   "stylise":[
      "style",
      "stylise",
      "stylize"
   ],
   "stylize":[
      "style",
      "stylise",
      "stylize"
   ],
   "stymy":[
      "stymy",
      "stymie"
   ],
   "stymie":[
      "stymy",
      "stymie"
   ],
   "suberise":[
      "suberise",
      "suberize"
   ],
   "suberize":[
      "suberise",
      "suberize"
   ],
   "sublime":[
      "sublime",
      "sublimate"
   ],
   "sublimate":[
      "sublime",
      "sublimate"
   ],
   "submerge":[
      "submerge",
      "submerse"
   ],
   "submerse":[
      "submerge",
      "submerse"
   ],
   "subminiaturise":[
      "subminiaturise",
      "subminiaturize"
   ],
   "subminiaturize":[
      "subminiaturise",
      "subminiaturize"
   ],
   "subside":[
      "subside",
      "subsidize",
      "subsidise"
   ],
   "subsidize":[
      "subside",
      "subsidize",
      "subsidise"
   ],
   "subsidise":[
      "subside",
      "subsidize",
      "subsidise"
   ],
   "substantivise":[
      "substantivise",
      "substantivize"
   ],
   "substantivize":[
      "substantivise",
      "substantivize"
   ],
   "subtilise":[
      "subtilise",
      "subtilize"
   ],
   "subtilize":[
      "subtilise",
      "subtilize"
   ],
   "suck":[
      "suck",
      "suction"
   ],
   "suction":[
      "suck",
      "suction"
   ],
   "sue":[
      "sue",
      "suit"
   ],
   "suit":[
      "sue",
      "suit"
   ],
   "sulfonate":[
      "sulfonate",
      "sulphonate"
   ],
   "sulphonate":[
      "sulfonate",
      "sulphonate"
   ],
   "sulphur":[
      "sulphur",
      "sulphurise",
      "sulphurize",
      "sulphurate"
   ],
   "sulphurise":[
      "sulphur",
      "sulphurise",
      "sulphurize",
      "sulphurate"
   ],
   "sulphurize":[
      "sulphur",
      "sulphurise",
      "sulphurize",
      "sulphurate"
   ],
   "sulphurate":[
      "sulphur",
      "sulphurise",
      "sulphurize",
      "sulphurate"
   ],
   "sum":[
      "sum",
      "summate"
   ],
   "summate":[
      "sum",
      "summate"
   ],
   "summarise":[
      "summarise",
      "summarize"
   ],
   "summarize":[
      "summarise",
      "summarize"
   ],
   "summer":[
      "summer",
      "summerize"
   ],
   "summerize":[
      "summer",
      "summerize"
   ],
   "summon":[
      "summon",
      "summons"
   ],
   "summons":[
      "summon",
      "summons"
   ],
   "swing":[
      "swing",
      "swinge"
   ],
   "swinge":[
      "swing",
      "swinge"
   ],
   "syllabify":[
      "syllabify",
      "syllabize",
      "syllabicate",
      "syllabification"
   ],
   "syllabize":[
      "syllabify",
      "syllabize",
      "syllabicate",
      "syllabification"
   ],
   "syllabicate":[
      "syllabify",
      "syllabize",
      "syllabicate",
      "syllabification"
   ],
   "syllabification":[
      "syllabify",
      "syllabize",
      "syllabicate",
      "syllabification"
   ],
   "syllogise":[
      "syllogise",
      "syllogize"
   ],
   "syllogize":[
      "syllogise",
      "syllogize"
   ],
   "symbolise":[
      "symbolise",
      "symbolize"
   ],
   "symbolize":[
      "symbolise",
      "symbolize"
   ],
   "symmetrize":[
      "symmetrize",
      "symmetrise"
   ],
   "symmetrise":[
      "symmetrize",
      "symmetrise"
   ],
   "sympathise":[
      "sympathise",
      "sympathize"
   ],
   "sympathize":[
      "sympathise",
      "sympathize"
   ],
   "synchronise":[
      "synchronise",
      "synchronize"
   ],
   "synchronize":[
      "synchronise",
      "synchronize"
   ],
   "syncretise":[
      "syncretise",
      "syncretize"
   ],
   "syncretize":[
      "syncretise",
      "syncretize"
   ],
   "synonymise":[
      "synonymise",
      "synonymize"
   ],
   "synonymize":[
      "synonymise",
      "synonymize"
   ],
   "synopsise":[
      "synopsise",
      "synopsize"
   ],
   "synopsize":[
      "synopsise",
      "synopsize"
   ],
   "synthesise":[
      "synthesise",
      "synthesize"
   ],
   "synthesize":[
      "synthesise",
      "synthesize"
   ],
   "systemize":[
      "systemize",
      "systematize"
   ],
   "systematize":[
      "systemize",
      "systematize"
   ],
   "table":[
      "table",
      "tabularize"
   ],
   "tabularize":[
      "table",
      "tabularize"
   ],
   "tamp":[
      "tamp",
      "tamper"
   ],
   "tamper":[
      "tamp",
      "tamper"
   ],
   "tantalise":[
      "tantalise",
      "tantalize"
   ],
   "tantalize":[
      "tantalise",
      "tantalize"
   ],
   "tartarise":[
      "tartarise",
      "tartarize"
   ],
   "tartarize":[
      "tartarise",
      "tartarize"
   ],
   "tat":[
      "tat",
      "tatt"
   ],
   "tatt":[
      "tat",
      "tatt"
   ],
   "teeth":[
      "teeth",
      "teethe"
   ],
   "teethe":[
      "teeth",
      "teethe"
   ],
   "temporise":[
      "temporise",
      "temporize"
   ],
   "temporize":[
      "temporise",
      "temporize"
   ],
   "tender":[
      "tender",
      "tenderise",
      "tenderize"
   ],
   "tenderise":[
      "tender",
      "tenderise",
      "tenderize"
   ],
   "tenderize":[
      "tender",
      "tenderise",
      "tenderize"
   ],
   "territorialise":[
      "territorialise",
      "territorialize"
   ],
   "territorialize":[
      "territorialise",
      "territorialize"
   ],
   "terrify":[
      "terrify",
      "terrorise",
      "terrorize"
   ],
   "terrorise":[
      "terrify",
      "terrorise",
      "terrorize"
   ],
   "terrorize":[
      "terrify",
      "terrorise",
      "terrorize"
   ],
   "tesselate":[
      "tesselate",
      "tessellate"
   ],
   "tessellate":[
      "tesselate",
      "tessellate"
   ],
   "tetanise":[
      "tetanise",
      "tetanize"
   ],
   "tetanize":[
      "tetanise",
      "tetanize"
   ],
   "teutonise":[
      "teutonise",
      "teutonize"
   ],
   "teutonize":[
      "teutonise",
      "teutonize"
   ],
   "theologise":[
      "theologise",
      "theologize"
   ],
   "theologize":[
      "theologise",
      "theologize"
   ],
   "theorise":[
      "theorise",
      "theorize"
   ],
   "theorize":[
      "theorise",
      "theorize"
   ],
   "tie":[
      "tie",
      "tying"
   ],
   "tying":[
      "tie",
      "tying"
   ],
   "till":[
      "till",
      "tiller"
   ],
   "tiller":[
      "till",
      "tiller"
   ],
   "ting":[
      "ting",
      "tinge"
   ],
   "tinge":[
      "ting",
      "tinge"
   ],
   "titivate":[
      "titivate",
      "tittivate"
   ],
   "tittivate":[
      "titivate",
      "tittivate"
   ],
   "top":[
      "top",
      "tope"
   ],
   "tope":[
      "top",
      "tope"
   ],
   "torrefy":[
      "torrefy",
      "torrify"
   ],
   "torrify":[
      "torrefy",
      "torrify"
   ],
   "total":[
      "total",
      "totalise",
      "totalize"
   ],
   "totalise":[
      "total",
      "totalise",
      "totalize"
   ],
   "totalize":[
      "total",
      "totalise",
      "totalize"
   ],
   "tranquilize":[
      "tranquilize",
      "tranquillize"
   ],
   "tranquillize":[
      "tranquilize",
      "tranquillize"
   ],
   "tranship":[
      "tranship",
      "transship"
   ],
   "transship":[
      "tranship",
      "transship"
   ],
   "transistorise":[
      "transistorise",
      "transistorize"
   ],
   "transistorize":[
      "transistorise",
      "transistorize"
   ],
   "transpire":[
      "transpire",
      "transpirate"
   ],
   "transpirate":[
      "transpire",
      "transpirate"
   ],
   "traumatise":[
      "traumatise",
      "traumatize"
   ],
   "traumatize":[
      "traumatise",
      "traumatize"
   ],
   "trichinise":[
      "trichinise",
      "trichinize"
   ],
   "trichinize":[
      "trichinise",
      "trichinize"
   ],
   "trivialise":[
      "trivialise",
      "trivialize"
   ],
   "trivialize":[
      "trivialise",
      "trivialize"
   ],
   "tropicalise":[
      "tropicalise",
      "tropicalize"
   ],
   "tropicalize":[
      "tropicalise",
      "tropicalize"
   ],
   "tuck":[
      "tuck",
      "tucker"
   ],
   "tucker":[
      "tuck",
      "tucker"
   ],
   "type":[
      "type",
      "typify"
   ],
   "typify":[
      "type",
      "typify"
   ],
   "tyrannise":[
      "tyrannise",
      "tyrannize"
   ],
   "tyrannize":[
      "tyrannise",
      "tyrannize"
   ],
   "uniform":[
      "uniform",
      "uniformize"
   ],
   "uniformize":[
      "uniform",
      "uniformize"
   ],
   "unite":[
      "unite",
      "unitize",
      "unionise",
      "unionize"
   ],
   "unitize":[
      "unite",
      "unitize",
      "unionise",
      "unionize"
   ],
   "unionise":[
      "unite",
      "unitize",
      "unionise",
      "unionize"
   ],
   "unionize":[
      "unite",
      "unitize",
      "unionise",
      "unionize"
   ],
   "universe":[
      "universe",
      "universalise",
      "universalize"
   ],
   "universalise":[
      "universe",
      "universalise",
      "universalize"
   ],
   "universalize":[
      "universe",
      "universalise",
      "universalize"
   ],
   "up":[
      "up",
      "ups"
   ],
   "ups":[
      "up",
      "ups"
   ],
   "urbanise":[
      "urbanise",
      "urbanize"
   ],
   "urbanize":[
      "urbanise",
      "urbanize"
   ],
   "utilise":[
      "utilise",
      "utilize"
   ],
   "utilize":[
      "utilise",
      "utilize"
   ],
   "vacate":[
      "vacate",
      "vacation"
   ],
   "vacation":[
      "vacate",
      "vacation"
   ],
   "valorise":[
      "valorise",
      "valorize"
   ],
   "valorize":[
      "valorise",
      "valorize"
   ],
   "value":[
      "value",
      "valuate"
   ],
   "valuate":[
      "value",
      "valuate"
   ],
   "vandalise":[
      "vandalise",
      "vandalize"
   ],
   "vandalize":[
      "vandalise",
      "vandalize"
   ],
   "vapor":[
      "vapor",
      "vaporise",
      "vaporize"
   ],
   "vaporise":[
      "vapor",
      "vaporise",
      "vaporize"
   ],
   "vaporize":[
      "vapor",
      "vaporise",
      "vaporize"
   ],
   "vary":[
      "vary",
      "variate"
   ],
   "variate":[
      "vary",
      "variate"
   ],
   "velarize":[
      "velarize",
      "velarise"
   ],
   "velarise":[
      "velarize",
      "velarise"
   ],
   "venge":[
      "venge",
      "avenge"
   ],
   "avenge":[
      "venge",
      "avenge"
   ],
   "ventriloquise":[
      "ventriloquise",
      "ventriloquize"
   ],
   "ventriloquize":[
      "ventriloquise",
      "ventriloquize"
   ],
   "verbalise":[
      "verbalise",
      "verbalize"
   ],
   "verbalize":[
      "verbalise",
      "verbalize"
   ],
   "vernalise":[
      "vernalise",
      "vernalize"
   ],
   "vernalize":[
      "vernalise",
      "vernalize"
   ],
   "victimise":[
      "victimise",
      "victimize"
   ],
   "victimize":[
      "victimise",
      "victimize"
   ],
   "vie":[
      "vie",
      "vying"
   ],
   "vying":[
      "vie",
      "vying"
   ],
   "visual":[
      "visual",
      "visualise",
      "visualize"
   ],
   "visualise":[
      "visual",
      "visualise",
      "visualize"
   ],
   "visualize":[
      "visual",
      "visualise",
      "visualize"
   ],
   "vitalise":[
      "vitalise",
      "vitalize"
   ],
   "vitalize":[
      "vitalise",
      "vitalize"
   ],
   "vitriolise":[
      "vitriolise",
      "vitriolize"
   ],
   "vitriolize":[
      "vitriolise",
      "vitriolize"
   ],
   "vocalise":[
      "vocalise",
      "vocalize"
   ],
   "vocalize":[
      "vocalise",
      "vocalize"
   ],
   "volatilise":[
      "volatilise",
      "volatilize"
   ],
   "volatilize":[
      "volatilise",
      "volatilize"
   ],
   "volcanize":[
      "volcanize",
      "volcanise"
   ],
   "volcanise":[
      "volcanize",
      "volcanise"
   ],
   "vowelise":[
      "vowelise",
      "vowelize"
   ],
   "vowelize":[
      "vowelise",
      "vowelize"
   ],
   "vulcanise":[
      "vulcanise",
      "vulcanize"
   ],
   "vulcanize":[
      "vulcanise",
      "vulcanize"
   ],
   "vulgarise":[
      "vulgarise",
      "vulgarize"
   ],
   "vulgarize":[
      "vulgarise",
      "vulgarize"
   ],
   "wait":[
      "wait",
      "await"
   ],
   "await":[
      "wait",
      "await"
   ],
   "wan":[
      "wan",
      "wane"
   ],
   "wane":[
      "wan",
      "wane"
   ],
   "weigh":[
      "weigh",
      "weight"
   ],
   "weight":[
      "weigh",
      "weight"
   ],
   "westernize":[
      "westernize",
      "westernise"
   ],
   "westernise":[
      "westernize",
      "westernise"
   ],
   "whisk":[
      "whisk",
      "whisker"
   ],
   "whisker":[
      "whisk",
      "whisker"
   ],
   "whiz":[
      "whiz",
      "whizz"
   ],
   "whizz":[
      "whiz",
      "whizz"
   ],
   "winter":[
      "winter",
      "winterize",
      "winterise"
   ],
   "winterize":[
      "winter",
      "winterize",
      "winterise"
   ],
   "winterise":[
      "winter",
      "winterize",
      "winterise"
   ],
   "wit":[
      "wit",
      "witness"
   ],
   "witness":[
      "wit",
      "witness"
   ],
   "womanise":[
      "womanise",
      "womanize"
   ],
   "womanize":[
      "womanise",
      "womanize"
   ],
   "wreath":[
      "wreath",
      "wreathe"
   ],
   "wreathe":[
      "wreath",
      "wreathe"
   ]
}
