alan_ask_types = {
	"money": [
		"finance_money",
		"finance_info",
		"scam_lottery",
		"scam_gift"
	],
	"information": [
		"personal",
		"business",
		"privileged_information",
		"credentials"
	],
	"performance": [
		"PERFORM"
	]
}

lose_verbs = [
	"abandon",
	"abash",
	"abduct",
	"abhor",
	"absolve",
	"abuse",
	"ache",
	"acquit",
	"afflict",
	"affront",
	"aggravate",
	"agitate",
	"agonize",
	"alarm",
	"alienate",
	"anger",
	"anguish",
	"annihilate",
	"annoy",
	"antagonize",
	"appal",
	"assassinate",
	"assuage",
	"backbite",
	"baffle",
	"balk",
	"bang",
	"bash",
	"bat",
	"batter",
	"beat",
	"beguile",
	"belt",
	"bereave",
	"beware",
	"bewilder",
	"bewitch",
	"bilk",
	"birch",
	"bite",
	"bleed",
	"blitz",
	"bludgeon",
	"boggle",
	"bonk",
	"bore",
	"boss",
	"bother",
	"brain",
	"brush",
	"bug",
	"bully",
	"bump",
	"bunt",
	"burgle",
	"butcher",
	"butt",
	"cadge",
	"calumniate",
	"cane",
	"capture",
	"care",
	"case",
	"castigate",
	"catapult",
	"censure",
	"chasten",
	"chastise",
	"cheat",
	"chide",
	"chuck",
	"claw",
	"cleanse",
	"clobber",
	"club",
	"con",
	"condemn",
	"confiscate",
	"confound",
	"confuse",
	"conk",
	"cop",
	"cosh",
	"crab",
	"crash",
	"cripple",
	"criticize",
	"crucify",
	"crush",
	"cry",
	"cudgel",
	"cuff",
	"cull",
	"cure",
	"cut",
	"dash",
	"daunt",
	"decimate",
	"decry",
	"defame",
	"defraud",
	"deject",
	"demolish",
	"demoralize",
	"denigrate",
	"denounce",
	"denude",
	"deny",
	"deplete",
	"deplore",
	"depopulate",
	"deprecate",
	"depress",
	"deprive",
	"deride",
	"desert",
	"despair",
	"despise",
	"despoil",
	"destroy",
	"detest",
	"devastate",
	"die",
	"dig",
	"disabuse",
	"disappear",
	"disappoint",
	"disapprove",
	"disarm",
	"discombobulate",
	"discomfit",
	"discompose",
	"disconcert",
	"discourage",
	"disdain",
	"disencumber",
	"disgrace",
	"disgruntle",
	"disgust",
	"dishearten",
	"disillusion",
	"dislike",
	"dismay",
	"disown",
	"disparage",
	"dispatch",
	"dispirit",
	"displease",
	"dispossess",
	"disquiet",
	"dissatisfy",
	"distract",
	"distress",
	"distrust",
	"disturb",
	"divest",
	"doubt",
	"drain",
	"dread",
	"drum",
	"ease",
	"electrocute",
	"eliminate",
	"emancipate",
	"embarass",
	"embezzle",
	"enrage",
	"envy",
	"exasperate",
	"execrate",
	"execute",
	"exhaust",
	"exonerate",
	"exorcise",
	"expire",
	"exterminate",
	"extirpate",
	"extort",
	"extract",
	"exult",
	"fault",
	"fear",
	"filch",
	"fine",
	"fire",
	"flabbergast",
	"fleece",
	"flick",
	"fling",
	"flip",
	"flog",
	"fluster",
	"forebode",
	"forfeit",
	"forget",
	"free",
	"fret",
	"frighten",
	"frustrate",
	"fume",
	"garrotte",
	"gloat",
	"grab",
	"grieve",
	"gripe",
	"grouch",
	"grumble",
	"gull",
	"gush",
	"hammer",
	"hang",
	"harass",
	"hate",
	"haunt",
	"hit",
	"horrify",
	"humiliate",
	"hunger",
	"hurl",
	"hurt",
	"hypnotize",
	"immolate",
	"impeach",
	"impound",
	"infuriate",
	"insult",
	"intimidate",
	"intoxicate",
	"irk",
	"irritate",
	"jab",
	"kick",
	"kidnap",
	"kill",
	"knife",
	"knock",
	"lambaste",
	"lament",
	"lapse",
	"lash",
	"liberate",
	"lift",
	"liquidate",
	"loathe",
	"lob",
	"loft",
	"lose",
	"madden",
	"malign",
	"martyr",
	"marvel",
	"massacre",
	"milk",
	"mock",
	"mollify",
	"mope",
	"mortify",
	"mourn",
	"muddle",
	"mulct",
	"murder",
	"nab",
	"nauseate",
	"nudge",
	"obliterate",
	"obsess",
	"offend",
	"orphan",
	"outlaw",
	"outrage",
	"overawe",
	"overwhelm",
	"paddle",
	"paddywhack",
	"pain",
	"pardon",
	"pass",
	"pauper",
	"paw",
	"peck",
	"penalize",
	"perish",
	"perplex",
	"persecute",
	"perturb",
	"pierce",
	"pilfer",
	"pinch",
	"pirate",
	"pitch",
	"pity",
	"plagiarize",
	"plague",
	"plunder",
	"poison",
	"poke",
	"pound",
	"preoccupy",
	"prick",
	"prosecute",
	"provoke",
	"pummel",
	"punch",
	"punish",
	"punt",
	"purge",
	"purify",
	"purloin",
	"puzzle",
	"rage",
	"ram",
	"rankle",
	"ransack",
	"rap",
	"ravage",
	"rave",
	"raze",
	"rebuke",
	"reclaim",
	"recover",
	"redeem",
	"regain",
	"regret",
	"relieve",
	"relinquish",
	"render",
	"repel",
	"repossess",
	"reprimand",
	"reproach",
	"reprove",
	"repulse",
	"rescue",
	"resent",
	"retrieve",
	"revile",
	"revolt",
	"rhapsodize",
	"rid",
	"ridicule",
	"rifle",
	"rob",
	"rue",
	"ruffle",
	"ruin",
	"rustle",
	"sacrifice",
	"sadden",
	"salivate",
	"sap",
	"scandalize",
	"scare",
	"scold",
	"scorn",
	"scratch",
	"seethe",
	"seize",
	"shake",
	"shame",
	"shock",
	"shoot",
	"shove",
	"sicken",
	"slam",
	"slap",
	"slaughter",
	"slay",
	"sling",
	"slug",
	"smack",
	"smash",
	"smother",
	"smuggle",
	"snatch",
	"sneak",
	"snub",
	"sock",
	"sorrow",
	"spank",
	"sponge",
	"spook",
	"stab",
	"stagger",
	"steal",
	"stick",
	"sting",
	"stir",
	"stone",
	"strangle",
	"strap",
	"strike",
	"strip",
	"stump",
	"stun",
	"stupefy",
	"suffer",
	"surrender",
	"suspect",
	"swat",
	"swindle",
	"swipe",
	"take",
	"tamp",
	"tantalize",
	"tap",
	"tease",
	"terrify",
	"terrorize",
	"thieve",
	"thrash",
	"threaten",
	"thrill",
	"throw",
	"thud",
	"thump",
	"thwack",
	"tip",
	"tire",
	"torment",
	"toss",
	"trouble",
	"truncheon",
	"try",
	"unburden",
	"unnerve",
	"unsettle",
	"upbraid",
	"uplift",
	"upset",
	"vanish",
	"vex",
	"victimize",
	"vilify",
	"void",
	"wallop",
	"wangle",
	"waste",
	"wean",
	"weary",
	"weasel",
	"weep",
	"whack",
	"whip",
	"whisk",
	"widow",
	"winkle",
	"withdraw",
	"wonder",
	"worry",
	"wound",
	"wreck",
	"wrest"
]

gain_verbs = [
	"accept",
	"accumulate",
	"acquire",
	"appropriate",
	"book",
	"borrow",
	"buy",
	"cadge",
	"call",
	"cash",
	"catch",
	"charter",
	"choose",
	"collect",
	"earn",
	"exact",
	"fetch",
	"find",
	"gain",
	"gather",
	"get",
	"grab",
	"hire",
	"inherit",
	"keep",
	"leave",
	"obtain",
	"order",
	"phone",
	"pick",
	"pluck",
	"procure",
	"pull",
	"reach",
	"receive",
	"recover",
	"regain",
	"reserve",
	"retrieve",
	"save",
	"secure",
	"seize",
	"select",
	"shoot",
	"slaughter",
	"snatch",
	"steal",
	"vote",
	"win"
]

perform_verbs = [
	"abduct",
	"absolve",
	"abstract",
	"acquit",
	"annihilate",
	"appraise",
	"arrange",
	"ask",
	"assassinate",
	"assess",
	"balk",
	"bereave",
	"bilk",
	"bleed",
	"blitz",
	"bring",
	"burgle",
	"butcher",
	"cable",
	"cadge",
	"cancel",
	"capture",
	"cheat",
	"check",
	"cleanse",
	"click",
	"con",
	"confirm",
	"confiscate",
	"connect",
	"consider",
	"contact",
	"contain",
	"contains",
	"cop",
	"copy",
	"copy-and-paste",
	"cull",
	"cure",
	"decimate",
	"defraud",
	"delete",
	"deliver",
	"demolish",
	"denude",
	"deplete",
	"depopulate",
	"deprive",
	"despoil",
	"destroy",
	"devastate",
	"disabuse",
	"disarm",
	"discharge",
	"disencumber",
	"disengage",
	"disgorge",
	"dislodge",
	"dismiss",
	"dispatch",
	"dispossess",
	"divest",
	"download",
	"drain",
	"draw",
	"e-mail",
	"ease",
	"eject",
	"eliminate",
	"emancipate",
	"embezzle",
	"eradicate",
	"estimate",
	"evict",
	"examine",
	"excise",
	"excommunicate",
	"execute",
	"exonerate",
	"exorcise",
	"expel",
	"exterminate",
	"extirpate",
	"extort",
	"extract",
	"extrude",
	"eye",
	"fax",
	"filch",
	"find",
	"fix",
	"fleece",
	"flog",
	"free",
	"glimpse",
	"grab",
	"gull",
	"help",
	"highlight",
	"immerse",
	"immolate",
	"impound",
	"inspect",
	"install",
	"investigate",
	"kidnap",
	"kill",
	"liberate",
	"lift",
	"liquidate",
	"lodge",
	"look",
	"lop",
	"massacre",
	"milk",
	"modem",
	"mount",
	"mulct",
	"murder",
	"nab",
	"netmail",
	"note",
	"notify",
	"obliterate",
	"observe",
	"omit",
	"open",
	"ostracize",
	"oust",
	"overhear",
	"pardon",
	"partition",
	"paste",
	"pay",
	"peg",
	"perceive",
	"phone",
	"pilfer",
	"pinch",
	"pirate",
	"place",
	"plagiarize",
	"plunder",
	"position",
	"price",
	"provide",
	"pry",
	"purchase",
	"purge",
	"purify",
	"purloin",
	"put",
	"radio",
	"ransack",
	"rate",
	"ravage",
	"raze",
	"read",
	"reap",
	"receive",
	"reclaim",
	"recover",
	"redeem",
	"refer",
	"regain",
	"register",
	"relay",
	"relieve",
	"remove",
	"render",
	"reply",
	"repossess",
	"request",
	"rescue",
	"reset",
	"respond",
	"retrieve",
	"review",
	"rid",
	"rifle",
	"rob",
	"rsvp",
	"ruin",
	"rustle",
	"sap",
	"satellite",
	"savor",
	"scan",
	"scent",
	"scrutinize",
	"see",
	"seize",
	"semaphore",
	"send",
	"separate",
	"set",
	"sever",
	"share",
	"shoo",
	"sign",
	"signal",
	"situate",
	"slaughter",
	"slay",
	"sling",
	"smuggle",
	"snatch",
	"sneak",
	"sponge",
	"start",
	"stash",
	"steal",
	"stow",
	"strip",
	"study",
	"submit",
	"subtract",
	"support",
	"survey",
	"swindle",
	"swipe",
	"take",
	"telecast",
	"telegraph",
	"telephone",
	"telex",
	"tell",
	"test",
	"thieve",
	"try",
	"type",
	"unburden",
	"unsubscribe",
	"update",
	"uproot",
	"value",
	"view",
	"visit",
	"void",
	"wangle",
	"waste",
	"watch",
	"wean",
	"weasel",
	"winkle",
	"wire",
	"wireless",
	"withdraw",
	"witness",
	"wreck",
	"wrench",
	"wrest"
]

give_verbs = [
	"administer",
	"advance",
	"airmail",
	"allocate",
	"allot",
	"assign",
	"award",
	"bequeath",
	"cede",
	"concede",
	"contribute",
	"convey",
	"covet",
	"crave",
	"credit",
	"deliver",
	"desire",
	"disburse",
	"dispatch",
	"distribute",
	"donate",
	"entrust",
	"express",
	"extend",
	"fancy",
	"fedex",
	"feed",
	"forfeit",
	"forward",
	"furnish",
	"give",
	"grant",
	"guarantee",
	"hand",
	"issue",
	"leave",
	"lend",
	"loan",
	"mail",
	"need",
	"offer",
	"owe",
	"pass",
	"pay",
	"peddle",
	"port",
	"post",
	"present",
	"proffer",
	"promise",
	"provide",
	"refer",
	"refund",
	"reimburse",
	"relinquish",
	"remit",
	"render",
	"rent",
	"repay",
	"restore",
	"return",
	"sacrifice",
	"send",
	"serve",
	"shift",
	"ship",
	"shunt",
	"slip",
	"smuggle",
	"sneak",
	"submit",
	"supply",
	"surrender",
	"transfer",
	"transport",
	"trust",
	"ups",
	"vote",
	"want",
	"will",
	"yield"
]

sashank_categories_sensitive = {
   "finance_money":[
      "money",
      "cash",
      "bit coin",
      "bitcoin",
      "cheque",
      "euro",
      "euros",
      "dollar",
      "dollars",
      "rupee",
      "rupees",
      "riyal",
      "riyals",
      "$",
      "£",
      "€",
      "₹"
   ],
   "finance_info":[
      "bank",
      "account",
      "transaction",
      "payment",
      "credit card",
      "insurance",
      "transaction",
      "tax",
      "claims",
      "irs",
      "fund",
      "account number",
      "account no",
      "direct deposit",
      "deposit",
      "beneficiary"
   ],
   "personal":[
      "email",
      "e-mail",
      "phone",
      "office address",
      "phone number",
      "contact info",
      "contact information",
      "cv",
      "personal",
      "photo",
      "mobile number",
      "mobile no",
      "phone no",
      "mobile num",
      "phone num",
      "social network",
      "twitter",
      "facebook",
      "social media"
   ],
   "personal_sensitive":[
      "ssn",
      "social security",
      "birthday",
      "citizenship",
      "originally from",
      "home address",
      "signature",
      "date of birth",
      "birth date",
      "day of birth"
   ],
   "business":[
      "proposal",
      "proposition",
      "offer",
      "investment",
      "collaboration",
      "partnership",
      "collusion",
      "business"
   ],
   "credentials":[
      "credentials",
      "password",
      "account",
      "slack id",
      "email id",
      "id",
      "user id",
      "login",
      "slack"
   ],
   "privileged_information":[
      "report",
      "document",
      "attachment",
      "files",
      "intellectual property",
      "brochure",
      "code",
      "form",
      "file",
      "software",
      "project",
      "dropbox",
      "github",
      "google drive",
      "gdrive",
      "excel",
      "word document",
      "word",
      "word doc",
      "doc",
      "slides",
      "presentation",
      "contract",
      "wiki",
      "gitlab",
      "ased",
      "testbed",
      "eval",
      "irb"
   ],
   "ideology":[
      "human rights",
      "jesus",
      "campaign",
      "health",
      "refugee",
      "humanitarian",
      "climate change",
      "cancer",
      "environment",
      "climate",
      "global warming",
      "autism",
      "activist",
      "charity",
      "donation",
      "flyer",
      "event",
      "celebration",
      "awareness",
      "migrant",
      "pet",
      "dog",
      "cat",
      "animal",
      "event",
      "donate",
      "election",
      "disaster",
      "relief"
   ],
   "scam_lottery":[
      "lottery",
      "lucky draw",
      "winner",
      "prize",
      "award"
   ],
   "scam_gift":[
      "gift",
      "present",
      "gift card",
      "gifts card",
      "shop",
      "store"
   ],
   "scam_job":[
      "job",
      "hiring",
      "work experience",
      "interview",
      "candidate",
      "indeed",
      "glassdoor",
      "linkedin",
      "LinkedIn",
      "hackerrank",
      "leetcode",
      "triplebyte",
      "recruiter"
   ],
   "phishing":[
      "link",
      "click here",
      "download",
      "join us",
      "upload here",
      "apply",
      "apply here",
      "surveymonkey",
      "survey monkey",
      "survey gizmo",
      "surveygizmo",
      "doodle",
      "surveyshare",
      "survey",
      "eventbrite",
      "event brite"
   ],
   "work_life":[
      "leave",
      "vacation",
      "sabbatical",
      "training",
      "training notice",
      "notice period",
      "resignation",
      "quit",
      "work from home",
      "family leave",
      "temporary work",
      "temporary work assignment",
      "sick leave"
   ]
}

# These types are not being used currently for sashanks types.
sashanks_ask_types = {
  "finance_money": [
    "11.1 Send Verbs",
    "13.1.a.i Give - No Exchange - Sort of Atelic",
    "13.1.a.ii Give - No Exchange",
    "13.2 Contribute Verbs",
    "13.3 Verbs of Future Having",
    "13.4.1.a Verbs of Fulfilling - Possessional / -to",
    "13.4.1.b Verbs of Fulfilling - Change of State / -with",
    "13.5.1.b.ii Get - Exchange",
    "13.5.2.a Obtain - No Exchange (CAUSE)",
    "13.5.2.b Obtain - No Exchange (LET w/ benefactive)",
	"32.1 Want Verbs"
  ],
  "finance_info": [
    "11.1 Send Verbs",
    "13.3 Verbs of Future Having",
    "13.4.1.a Verbs of Fulfilling - Possessional / -to",
    "13.4.1.b Verbs of Fulfilling - Change of State / -with",
    "13.5.1.b.ii Get - Exchange",
    "13.5.2.b Obtain - No Exchange (LET w/ benefactive)",
    "37.2.a Tell Verbs",
    "37.2.b Tell Verbs / -of/about",
    "37.2.d Tell Verbs / -that/to",
	"32.1 Want Verbs"
  ],
  "personal": [
    "11.1 Send Verbs",
    "13.3 Verbs of Future Having",
    "13.4.1.a Verbs of Fulfilling - Possessional / -to",
    "13.4.1.b Verbs of Fulfilling - Change of State / -with",
    "13.5.2.b Obtain - No Exchange (LET w/ benefactive)",
    "37.2.a Tell Verbs",
    "37.2.b Tell Verbs / -of/about",
    "37.2.d Tell Verbs / -that/to",
	"32.1 Want Verbs"
  ],
  "business": [
    "13.3 Verbs of Future Having"
  ],
  "credentials": [
    "11.1 Send Verbs",
    "13.1.a.ii Give - No Exchange",
    "13.3 Verbs of Future Having",
    "13.4.1.a Verbs of Fulfilling - Possessional / -to",
    "13.4.1.b Verbs of Fulfilling - Change of State / -with",
    "13.5.2.b Obtain - No Exchange (LET w/ benefactive)",
    "37.2.a Tell Verbs",
    "37.2.b Tell Verbs / -of/about",
    "37.2.d Tell Verbs / -that/to",
	"32.1 Want Verbs"
  ],
  "privileged_information": [
    "11.1 Send Verbs",
    "13.1.a.ii Give - No Exchange",
    "13.3 Verbs of Future Having",
    "13.4.1.a Verbs of Fulfilling - Possessional / -to",
    "13.4.1.b Verbs of Fulfilling - Change of State / -with",
    "13.5.2.b Obtain - No Exchange (LET w/ benefactive)",
    "37.2.a Tell Verbs",
    "37.2.b Tell Verbs / -of/about",
    "37.2.d Tell Verbs / -that/to",
	"32.1 Want Verbs"
  ],
  "ideology": [],
  "scam_lottery": [
    "13.5.2.c Obtain - No Exchange (LET w/out benefactive)"
  ],
  "scam_gift": [
    "13.5.2.c Obtain - No Exchange (LET w/out benefactive)"
  ],
  "scam_job": []
}

tomeks_ask_types = {
  "LOSE": [ #verbs may need to be used differently in their passive (victim in subject) vs active form (victim in DO) for this class but not focused on that for now
    #"10.5.p Panacea Lose related Verbs", #REMOVED AS NOT IN ORIGINAL LCS
    "10.5 Verbs of Possessional Deprivation : Steal Verbs",
    "10.6.a Verbs of Possessional Deprivation : Cheat Verbs / -of",
    "10.6.c Verbs of Possessional Deprivation : Cheat Verbs / -out of",
    "17.1 Throw Verbs",
    "17.2.i Pelt Verbs",
    "17.2.ii Pelt Verbs -- stone",
    "18.1.a Hit Verbs - Change of State / -with",
    "18.1.b Hit Verbs - Change of State",
    "18.1.c Hit Verbs  - Locational / -at/with",
    "18.1.d Hit Verbs  - Locational / against",
    "18.1.e Hit Verbs  - Change of State / together",
    "18.2.a Swat Verbs",
    "18.2.b Swat Verbs  - Locational",
    "18.3 Spank Verbs",
    "18.4.a Nonagentive Verbs of Impact by Contact - Locational",
    "18.4.b Nonagentive Verbs of Impact by Contact - Change of State",
    "19.a.i Poke Verbs",
    "19.a.ii Poke Verbs - Change of State",
    "19.b Poke Verbs - Locational / -through",
    "19.c.i Poke Verbs / -with",
    "19.c.ii Poke Verbs - Change of State / -with",
    "19.d Poke Verbs - Locational / -with",
    #"29.2.b.p Characterize Verbs / -S", #USED ORIGINAL
    "29.2.b. Characterize Verbs / -S",
    #"29.7.p Panacea Orphan Verbs", #USED ORIGINAL
    "29.7 Orphan Verbs",
    #"29.8.a.p Panacea Captain Verbs / Beneficiary", #USED ORIGINAL
    "29.8.a Captain Verbs / Beneficiary",
    #"31.1.a.p Panacea Amuse Verbs / -with", #USED ORIGINAL
    "31.1.a Amuse Verbs / -with",
    #"31.2.b.p Panacea Admire Verbs - Positive / -in", #USED ORIGINAL
    "31.2.b Admire Verbs - Positive / -in",
    "31.2.d Admire Verbs - Negative / -for/as",
    #"31.3.c.p Panacea Marvel Verbs / -for", #USED ORIGINAL
    "31.3.c Marvel Verbs / -for",
    #"31.3.d.p Panacea Marvel Verbs / -from", #USED ORIGINAL
    "31.3.d Marvel Verbs / -from",
    #"31.3.f.p Panacea Marvel Verbs / -of", #USED ORIGINAL
    "31.3.f Marvel Verbs / -of",
    #"31.3.h.p Panacea Marvel Verbs / -over", #USED ORIGINAL
    "31.3.h Marvel Verbs / -over",
    #"33.b Panacea Judgment Verbs - Negative / -for/as", #USED ORIGINAL
    "33.b Judgment Verbs - Negative / -for/as",
    "37.8.a Complain Verbs / -that/to",
    "37.8.b Complain Verbs / -about/to",
    "42.1.a Murder Verbs - Kill",
    "42.1.c Murder Verbs - General",
    "42.2 Poison Verbs",
    "44.a Destroy Verbs / -with",
    "48.2 Verbs of Disappearance",
    "51.2 Leave Verbs"
    #added these to Steal verbs class for now: "29.5.b Conjecture Verbs / -that", #only some of these verbs ([doubt, suspect, forebode]) but not all!
    #added (cripple martyr orphan outlaw) from "29.7 Orphan Verbs" to "10.5 Verbs of Possessional Deprivation : Steal Verbs"
    #added (butcher bully), (lose disown deny forfeit relinquish sacrifice surrender ache hurt suffer grieve anguish mourn) from other categories, such as from "13.2", "31.3.d" etc
    #moved additionally added verbs in 10.5 to a new category called "10.5.1.a Panacea Lose related Verbs"
           
  ],
  "GAIN": [
    "13.5.1.a Get - No Exchange",
    "13.5.1.b.ii Get - Exchange",
    "13.5.2.a Obtain - No Exchange (CAUSE)",
    "13.5.2.b Obtain - No Exchange (LET w/ benefactive)",
    "13.5.2.c Obtain - No Exchange (LET w/out benefactive)"
    #"32.1 Want Verbs"
  ],
  "GIVE": [
    "11.1 Send Verbs",
    "13.1.a.i Give - No Exchange - Sort of Atelic",
    "13.1.a.ii Give - No Exchange",
    "13.2 Contribute Verbs",
    "13.3 Verbs of Future Having",
    "13.4.1.a Verbs of Fulfilling - Possessional / -to",
    "13.4.1.b Verbs of Fulfilling - Change of State / -with",
    "32.1 Want Verbs"
  ],
  "APPLY": [],
  "PERFORM": [
    "9.1 Put Verbs",
    "10.1 Remove Verbs",
    "10.2.b Banish Verbs / -to",
    "10.5 Verbs of Possessional Deprivation : Steal Verbs",
    "10.6.a Verbs of Possessional Deprivation : Cheat Verbs / -of",
    "10.6.c Verbs of Possessional Deprivation : Cheat Verbs / -out of",
    "11.3 Bring and Take Verbs",
    "13.5.2.d Obtain - Exchange",
    #"30.2.a.i.p Panacea Sight Verbs / Bare NP", #USED ORIGINAL
    "30.2.a.i Sight Verbs / Bare NP",
    "37.1.e Verbs of Transfer of a Message / -that/to",
    "37.2.a Tell Verbs",
    "37.2.b Tell Verbs / -of/about",
    "37.2.d Tell Verbs / -that/to",
    "37.4.a Verbs of Instrument of Communication",
    "42.1.a Murder Verbs - Kill",
    "42.1.b Murder Verbs - Kill / -with",
    "42.1.c Murder Verbs - General",
    "44.a Destroy Verbs / -with",
    "44.b Destroy Verbs / Instrument Subject",
    "54.4 Price Verbs"
  ],
  "OTHER": []
}
